/* ---------- v4.6 · BLOQUES INTERACTIVOS ----------
   · dx_finder  — comparador de tarifas con filtros (velocidad, líneas, cobertura…) y orden por precio.
   · dx_bundle  — «configura tu pack»: el visitante marca lo que quiere, ve el total y lo envía (llega como campo pack).
   · dx_booking — pide cita: días laborables siguientes + franjas; llega como cita_dia y cita_hora.
   · dx_vtestis — testimonios en vídeo con portada y botón de play (el vídeo solo carga al pulsar, en ventana).
   Todo cableado a los canales medibles. Precios, nombres, vídeos y opiniones: siempre los reales o {{PLACEHOLDER}}. */
Object.assign(LIB,{
dx_finder:{label:"✚ Comparador de tarifas con filtros",ico:"⚲",cat:"Extras CRO",raw:true,
  def:()=>({title:"Encuentra tu tarifa",sub:"Marca lo que necesitas y te enseñamos solo lo que encaja.",filters:"Velocidad|300 Mb,600 Mb,1 Gb\nMóvil|Sin móvil,1 línea,2 líneas",act:"popup",
    plans:[{name:"{{TARIFA_1}}",price:"{{PRECIO_1}}",unit:"€/mes",feats:"Fibra {{VELOCIDAD_1}}",tags:"300 Mb,Sin móvil",tag:"",cta:"La quiero"},{name:"{{TARIFA_2}}",price:"{{PRECIO_2}}",unit:"€/mes",feats:"Fibra {{VELOCIDAD_2}}\nMóvil {{GB_2}}",tags:"600 Mb,1 línea",tag:"La más elegida",cta:"La quiero"},{name:"{{TARIFA_3}}",price:"{{PRECIO_3}}",unit:"€/mes",feats:"Fibra {{VELOCIDAD_3}}\n2 líneas {{GB_3}}",tags:"1 Gb,2 líneas",tag:"",cta:"La quiero"}],
    empty:"No hay ninguna tarifa con esa combinación. Te llamamos y te buscamos la tuya.",emptyBtn:"Que me llamen"}),
  fields:[{k:"title",l:"Título"},{k:"sub",l:"Subtítulo"},{k:"filters",l:"Filtros (Grupo|opción1,opción2… una línea por grupo)",t:"ta"},V4_ACTF,
    {k:"plans",l:"Tarifas",t:"repeater",addLabel:"Añadir tarifa",item:[{k:"name",l:"Nombre",def:"Tarifa"},{k:"price",l:"Precio",def:"{{PRECIO}}"},{k:"unit",l:"Unidad",def:"€/mes"},{k:"feats",l:"Incluye (una por línea)",t:"ta",def:""},{k:"tags",l:"Encaja con (opciones de los filtros, separadas por comas)",def:""},{k:"tag",l:"Etiqueta",def:""},{k:"cta",l:"Botón",def:"La quiero"}]},
    {k:"empty",l:"Mensaje si no hay resultados"},{k:"emptyBtn",l:"Botón si no hay resultados"}],
  render:p=>{const groups=v4L(p.filters).map(l=>{const c=l.split("|");return {g:(c[0]||"").trim(),o:(c[1]||"").split(",").map(x=>x.trim()).filter(Boolean)};}).filter(x=>x.g&&x.o.length);
    return `<section class="da da-sec dx-fnd" id="tarifas" data-finder><div class="container"><div class="text-center mb-4"><h2 class="da-h2">${esc(p.title)}</h2><p class="da-muted">${esc(p.sub)}</p></div>
    <div class="dx-fnd-f">${groups.map((g,gi)=>`<div class="grp" data-g="${gi}"><span class="gl">${esc(g.g)}</span><div class="ops"><button type="button" class="op on" data-v="">Todas</button>${g.o.map(o=>`<button type="button" class="op" data-v="${esc(o)}">${esc(o)}</button>`).join("")}</div></div>`).join("")}
      <div class="grp srt"><span class="gl">Ordenar</span><div class="ops"><button type="button" class="op on" data-sort="">Recomendadas</button><button type="button" class="op" data-sort="price">Precio</button></div></div></div>
    <p class="dx-fnd-n" aria-live="polite"><b data-fnd-n>${arr(p.plans).length}</b> tarifas</p>
    <div class="row g-4 justify-content-center dx-fnd-l">${arr(p.plans).map((pl,i)=>{const best=!!pl.tag;return `<div class="col-md-6 col-lg-4" data-tags="${esc(String(pl.tags||"").split(",").map(x=>x.trim()).join("|"))}" data-price="${esc(String(pl.price||"").replace(",","."))}" data-i="${i}"><div class="da-plan ${best?"best":""}">${pl.tag?`<span class="tag">${esc(pl.tag)}</span>`:""}<h3>${esc(pl.name)}</h3><div class="pp">${esc(pl.price)}<small>${esc(pl.unit||"")}</small></div>${v4Checks(pl.feats,"")}<a href="#form" data-cta="form"${v4ActA(p,pl)} class="da-btn ${best?"pri":"sec"} w-100 justify-content-center">${esc(pl.cta||"La quiero")}</a></div></div>`;}).join("")}</div>
    <div class="dx-fnd-e" hidden><p>${esc(p.empty)}</p><a href="#form" data-cta="form"${v4ActA(p)} class="da-btn pri">${esc(p.emptyBtn||"Que me llamen")}</a></div></div></section>`;}},
dx_bundle:{label:"✚ Configura tu pack (total en vivo)",ico:"☑",cat:"Extras CRO",raw:true,
  def:()=>({title:"Configura tu pack",sub:"Marca lo que quieres y te decimos el precio final por teléfono.",base:"",baseLabel:"",unit:"€/mes",items:"Fibra {{VELOCIDAD}}|{{PRECIO_FIBRA}}|on\nLínea móvil {{GB}}|{{PRECIO_MOVIL}}|\nTV {{PAQUETE_TV}}|{{PRECIO_TV}}|\nSegunda línea|{{PRECIO_LINEA_2}}|",note:"Precios con IVA. El total es orientativo hasta que te lo confirmamos.",btn:"Quiero este pack",act:"form",ph:"Tu teléfono"}),
  fields:[{k:"title",l:"Título"},{k:"sub",l:"Subtítulo"},{k:"items",l:"Opciones (nombre|precio|on = marcada)",t:"ta"},{k:"base",l:"Precio base (opcional, se suma siempre)"},{k:"baseLabel",l:"Qué incluye el precio base"},{k:"unit",l:"Unidad"},{k:"note",l:"Nota"},{k:"btn",l:"Botón"},
    {k:"act",l:"Al enviar",t:"select",opts:[["form","Formulario aquí mismo"],["popup","Abrir el popup con el pack"],["call","Llamar"],["wa","WhatsApp con el pack"]]}],
  render:p=>{const L=v4L(p.items).map(l=>{const c=v4C(l);return {n:c[0]||"",pr:c[1]||"",on:/^(on|si|sí|1)$/i.test(c[2]||"")};});
    const btn=p.act==="call"?`${v4Tel()} class="da-btn pri w-100 justify-content-center">${I_TEL()} ${esc(p.btn)}</a>`:p.act==="wa"?`<a href="${waHref()}" target="_blank" rel="noopener" data-cta="whatsapp" data-bundle-wa class="da-btn pri wa w-100 justify-content-center">${I_WA()} ${esc(p.btn)}</a>`
      :p.act==="popup"?`<a href="#form" data-cta="form" data-act="popup" data-bundle-cta class="da-btn pri w-100 justify-content-center">${esc(p.btn)} ${I_GO()}</a>`
      :`<form data-callback action="${v4Act()}" method="post" class="dx-bnd-form" id="form"><input type="hidden" name="pack" data-bundle-field><input type="hidden" name="pack_total" data-bundle-total><input required name="telefono" type="tel" class="form-control" placeholder="${esc(p.ph||vt("phone"))}" autocomplete="tel"><button type="submit" class="da-go">${esc(p.btn)}</button></form>`;
    return `<section class="da da-sec soft dx-bnd" data-bundle data-unit="${esc(p.unit||"")}" data-base="${esc(String(p.base||"").replace(",","."))}"><div class="container"><div class="row g-4 g-lg-5 align-items-start">
    <div class="col-lg-7"><h2 class="da-h2">${esc(p.title)}</h2><p class="da-muted mb-4">${esc(p.sub)}</p><div class="dx-bnd-l">${L.map((it,i)=>`<label class="dx-bnd-it"><input type="checkbox" data-n="${esc(it.n)}" data-p="${esc(String(it.pr).replace(",","."))}"${it.on?" checked":""}><span class="bx" aria-hidden="true"></span><span class="nm">${esc(it.n)}</span><span class="pr">${esc(it.pr)}${it.pr&&!/\{\{/.test(it.pr)?` <small>${esc(p.unit||"")}</small>`:""}</span></label>`).join("")}</div></div>
    <div class="col-lg-5"><div class="da-card dx-bnd-sum"><div class="lb">Tu pack</div><ul data-bundle-list></ul>${p.base?`<div class="bs">${esc(p.baseLabel||"Base")} · ${esc(p.base)} ${esc(p.unit||"")}</div>`:""}
      <div class="tt"><span>Total</span><b data-bundle-sum>—</b></div><p class="nt">${esc(p.note)}</p>${btn}</div></div></div></div></section>`;}},
dx_booking:{label:"✚ Pide cita (día y hora)",ico:"🗓",cat:"Extras CRO",raw:true,
  def:()=>({title:"Elige cuándo te llamamos",sub:"Escoge día y franja y un asesor te llama a esa hora. Sin compromiso.",days:"6",sat:"",slots:"9:00 – 11:00|11:00 – 13:00|16:00 – 18:00|18:00 – 20:00",btn:"Reservar mi llamada",name:"si",note:"Te enviamos la confirmación por SMS o WhatsApp."}),
  fields:[{k:"title",l:"Título"},{k:"sub",l:"Subtítulo"},{k:"days",l:"Días que se ofrecen",t:"select",opts:[["4","4"],["6","6"],["8","8"],["10","10"]]},{k:"sat",l:"Incluir sábados",t:"select",opts:[["","No"],["1","Sí"]]},{k:"slots",l:"Franjas (separadas por |)"},{k:"name",l:"Pedir nombre",t:"select",opts:[["si","Sí"],["no","No"]]},{k:"btn",l:"Botón"},{k:"note",l:"Nota"}],
  render:p=>`<section class="da da-sec dx-bk" data-booking data-days="${esc(p.days||"6")}" data-sat="${p.sat?"1":""}"><div class="container" style="max-width:860px"><div class="text-center mb-4"><h2 class="da-h2">${esc(p.title)}</h2><p class="da-muted">${esc(p.sub)}</p></div>
    <div class="da-card dx-bk-c"><form data-callback action="${v4Act()}" method="post" id="form"><input type="hidden" name="cita_dia" data-bk-day><input type="hidden" name="cita_hora" data-bk-slot>
      <div class="lb">1 · Día</div><div class="dx-bk-days" data-bk-days role="radiogroup" aria-label="Día"></div>
      <div class="lb">2 · Hora</div><div class="dx-bk-slots" role="radiogroup" aria-label="Franja">${String(p.slots||"").split("|").map(x=>x.trim()).filter(Boolean).map(s=>`<button type="button" class="dx-bk-s" data-slot="${esc(s)}" aria-pressed="false">${esc(s)}</button>`).join("")}</div>
      <div class="lb">3 · Tus datos</div><div class="dx-bk-in">${p.name==="no"?"":`<input required name="nombre" class="form-control" placeholder="Nombre" autocomplete="name">`}<input required name="telefono" type="tel" class="form-control" placeholder="${esc(vt("phone"))}" autocomplete="tel"></div>
      <p class="dx-bk-sel" data-bk-sel aria-live="polite">Elige día y hora.</p><button type="submit" class="da-go">${esc(p.btn)}</button><p class="dx-bk-nt">${esc(p.note)}</p></form></div></div></section>`},
dx_vtestis:{label:"✚ Testimonios en vídeo",ico:"▶",cat:"Extras CRO",raw:true,
  def:()=>({title:"Te lo cuentan nuestros clientes",sub:"Vídeos de menos de un minuto, con subtítulos.",items:[{video:"",poster:"",name:"{{NOMBRE_1}}",meta:"{{CIUDAD_1}}",quote:"{{FRASE_1}}"},{video:"",poster:"",name:"{{NOMBRE_2}}",meta:"{{CIUDAD_2}}",quote:"{{FRASE_2}}"},{video:"",poster:"",name:"{{NOMBRE_3}}",meta:"{{CIUDAD_3}}",quote:"{{FRASE_3}}"}],btn:"Quiero lo mismo",act:"popup"}),
  fields:[{k:"title",l:"Título"},{k:"sub",l:"Subtítulo"},{k:"items",l:"Vídeos",t:"repeater",addLabel:"Añadir vídeo",item:[{k:"video",l:"Vídeo (enlace de YouTube, Vimeo o .mp4)",def:""},{k:"poster",l:"Portada (foto del cliente)",t:"image",def:""},{k:"name",l:"Nombre",def:"{{NOMBRE}}"},{k:"meta",l:"Ciudad / servicio",def:""},{k:"quote",l:"Frase destacada",def:""}]},{k:"btn",l:"Botón bajo los vídeos (vacío = sin botón)"},V4_ACTF],
  render:p=>`<section class="da da-sec dx-vt"><div class="container"><div class="text-center mb-4 mb-lg-5"><h2 class="da-h2">${esc(p.title)}</h2>${p.sub?`<p class="da-muted">${esc(p.sub)}</p>`:""}</div>
    <div class="row g-4 justify-content-center">${arr(p.items).map(it=>`<div class="col-md-6 col-lg-4"><figure class="dx-vt-c"><button type="button" class="dx-vt-p" data-video="${esc(it.video||"")}" aria-label="Ver el vídeo de ${esc(it.name||"cliente")}">${it.poster?`<img src="${it.poster}" alt="${esc(it.name||"")}" loading="lazy">`:`<span class="ph">{{VIDEO}}</span>`}<span class="pl" aria-hidden="true"><svg viewBox="0 0 24 24" width="26" height="26"><path d="M8 5v14l11-7z" fill="currentColor"/></svg></span></button>
      <figcaption>${it.quote?`<q>${esc(it.quote)}</q>`:""}<b>${esc(it.name||"")}</b>${it.meta?`<small>${esc(it.meta)}</small>`:""}</figcaption></figure></div>`).join("")}</div>
    ${p.btn?`<div class="da-btns justify-content-center"><a href="#form" data-cta="form"${v4ActA(p)} class="da-btn pri">${esc(p.btn)} ${I_GO()}</a></div>`:""}</div></section>`}
});
(function(){const X=["dx_finder","dx_bundle","dx_booking","dx_vtestis"];let i=ORDER.indexOf("dx_calc");if(i<0)i=ORDER.length;else i++;ORDER.splice(i,0,...X);})();
const NC_PLUS_TYPES=/^dx_(finder|bundle|booking|vtestis)$/;
function ncPlusCSS(){return `
.dx-fnd-f{display:flex;flex-direction:column;gap:12px;max-width:900px;margin:0 auto 18px}.dx-fnd-f .grp{display:flex;flex-wrap:wrap;align-items:center;gap:8px 12px}.dx-fnd-f .gl{font-weight:700;font-size:14px;color:var(--bink);min-width:90px}
.dx-fnd-f .ops{display:flex;flex-wrap:wrap;gap:6px}.dx-fnd-f .op{border:1.5px solid var(--dline);background:#fff;color:var(--bink);border-radius:999px;padding:7px 14px;font-size:14px;font-weight:600;cursor:pointer}.dx-fnd-f .op.on{background:var(--bink);border-color:var(--bink);color:#fff}
.dx-fnd-n{text-align:center;color:var(--bmuted);font-size:14px;margin:0 0 18px}.dx-fnd-l>[hidden]{display:none!important}.dx-fnd-e{text-align:center;max-width:520px;margin:10px auto 0}.dx-fnd-e p{color:var(--bmuted)}
@media (max-width:575px){.dx-fnd-f .gl{min-width:0;flex:1 1 100%}}
.dx-bnd-l{display:flex;flex-direction:column;gap:10px}.dx-bnd-it{display:flex;align-items:center;gap:14px;background:#fff;border:1.5px solid var(--dline);border-radius:var(--cardr,16px);padding:16px 18px;cursor:pointer;color:var(--bink);transition:border-color .15s,box-shadow .15s}
.dx-bnd-it input{position:absolute;opacity:0;pointer-events:none}.dx-bnd-it .bx{width:24px;height:24px;border-radius:7px;border:2px solid var(--dline);flex:0 0 auto;display:grid;place-items:center}
.dx-bnd-it input:checked~.bx{background:var(--bp);border-color:var(--bp)}.dx-bnd-it input:checked~.bx::after{content:"";width:7px;height:12px;border:solid var(--btntext,#fff);border-width:0 2.5px 2.5px 0;transform:rotate(45deg) translate(-1px,-1px)}
.dx-bnd-it:has(input:checked){border-color:var(--bp);box-shadow:0 0 0 3px color-mix(in srgb,var(--bp) 14%,transparent)}.dx-bnd-it input:focus-visible~.bx{outline:2px solid var(--bp);outline-offset:2px}
.dx-bnd-it .nm{flex:1;min-width:0;font-weight:700;font-size:16px;overflow-wrap:anywhere}.dx-bnd-it .pr{font-weight:800;font-family:var(--fdisp,var(--fhead));text-align:right;min-width:0;overflow-wrap:anywhere;max-width:45%}.dx-bnd-it .pr small{font-weight:600;color:var(--bmuted);font-size:12px}
.dx-bnd-sum{position:sticky;top:90px}.dx-bnd-sum .lb{font-size:12.5px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--bmuted)}.dx-bnd-sum ul{list-style:none;padding:0;margin:10px 0;min-height:24px}.dx-bnd-sum li{padding:6px 0;border-bottom:1px dashed var(--dline);font-size:14.5px}
.dx-bnd-sum .bs{font-size:13px;color:var(--bmuted);margin-bottom:6px}.dx-bnd-sum .tt{display:flex;justify-content:space-between;align-items:baseline;margin:10px 0 4px}.dx-bnd-sum .tt b{font:800 34px/1 var(--fdisp,var(--fhead));letter-spacing:-.03em}.dx-bnd-sum .nt{font-size:12.5px;color:var(--bmuted)}
.dx-bnd-form{display:flex;flex-direction:column;gap:8px}.dx-bnd-form .form-control{border-radius:12px;padding:14px}
@media (max-width:991px){.dx-bnd-sum{position:static}}
.dx-bk-c .lb{font-weight:700;font-size:14px;margin:4px 0 8px;color:var(--bink)}.dx-bk-days{display:grid;grid-template-columns:repeat(auto-fill,minmax(88px,1fr));gap:8px;margin-bottom:16px}
.dx-bk-d,.dx-bk-s{border:1.5px solid var(--dline);background:#fff;color:var(--bink);border-radius:12px;padding:10px 8px;cursor:pointer;text-align:center;line-height:1.15}.dx-bk-d small{display:block;font-size:11.5px;color:var(--bmuted);text-transform:capitalize}.dx-bk-d b{display:block;font-size:20px;font-family:var(--fdisp,var(--fhead))}
.dx-bk-d[aria-pressed="true"],.dx-bk-s[aria-pressed="true"]{border-color:var(--bp);background:color-mix(in srgb,var(--bp) 10%,#fff);box-shadow:0 0 0 2px var(--bp) inset}.dx-bk-d[aria-pressed="true"] small{color:var(--bink)}
.dx-bk-slots{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}.dx-bk-s{padding:10px 14px;font-weight:600;font-size:14px}
.dx-bk-in{display:flex;flex-wrap:wrap;gap:8px}.dx-bk-in .form-control{flex:1 1 200px;border-radius:12px;padding:13px}.dx-bk-sel{font-size:14px;color:var(--bmuted);margin:12px 0 8px}.dx-bk-sel b{color:var(--bink)}.dx-bk-nt{font-size:12.5px;color:var(--bmuted);margin:10px 0 0;text-align:center}
.dx-vt-c{margin:0;height:100%;display:flex;flex-direction:column;background:#fff;border:1px solid var(--dline);border-radius:var(--cardr,18px);overflow:hidden;color:var(--bink)}
.dx-vt-p{position:relative;display:block;width:100%;aspect-ratio:4/5;border:0;padding:0;background:color-mix(in srgb,var(--bp) 18%,#111);cursor:pointer;overflow:hidden}.dx-vt-p img{width:100%;height:100%;object-fit:cover;transition:transform .4s}.dx-vt-p:hover img{transform:scale(1.03)}
.dx-vt-p .ph{position:absolute;inset:0;display:grid;place-items:center;color:rgba(255,255,255,.75);font-weight:700}.dx-vt-p .pl{position:absolute;left:50%;top:50%;width:66px;height:66px;margin:-33px 0 0 -33px;border-radius:50%;background:#fff;color:var(--ink0,#111);display:grid;place-items:center;box-shadow:0 10px 30px rgba(0,0,0,.35)}
.dx-vt-c figcaption{padding:16px 18px 18px}.dx-vt-c q{display:block;font-weight:600;font-size:15.5px;line-height:1.4;margin-bottom:10px;quotes:"“" "”"}.dx-vt-c b{display:block;font-size:14px}.dx-vt-c small{color:var(--bmuted);font-size:12.5px}
.dx-vt .da-btns{margin-top:28px}
.nc-vbox{position:fixed;inset:0;z-index:1080;background:rgba(0,0,0,.82);display:grid;place-items:center;padding:16px}.nc-vbox>div{width:min(420px,100%);aspect-ratio:9/16;max-height:86vh;background:#000;border-radius:14px;overflow:hidden;position:relative}.nc-vbox.wide>div{width:min(960px,100%);aspect-ratio:16/9}
.nc-vbox iframe,.nc-vbox video{width:100%;height:100%;border:0;display:block}.nc-vbox button{position:absolute;top:10px;right:10px;z-index:2;border:0;border-radius:50%;width:38px;height:38px;background:rgba(255,255,255,.92);font-size:20px;line-height:1;cursor:pointer}`;}
const NC_PLUS_JS=`(function(){var DL=function(o){try{(window.dataLayer=window.dataLayer||[]).push(o);}catch(e){}};
function num(s){var v=parseFloat(String(s||'').replace(',','.'));return isNaN(v)?null:v;}function fmt(v){return v.toLocaleString('es-ES',{minimumFractionDigits:v%1?2:0,maximumFractionDigits:2});}
document.querySelectorAll('[data-finder]').forEach(function(w){var sel={},sort='';var cards=[].slice.call(w.querySelectorAll('[data-tags]'));var list=w.querySelector('.dx-fnd-l');var n=w.querySelector('[data-fnd-n]');var em=w.querySelector('.dx-fnd-e');
  function apply(){var vis=0;cards.forEach(function(c){var tg=(c.getAttribute('data-tags')||'').split('|');var ok=Object.keys(sel).every(function(g){return !sel[g]||tg.indexOf(sel[g])>-1;});c.hidden=!ok;if(ok)vis++;});
    var ord=cards.slice();if(sort==='price')ord.sort(function(a,b){var x=num(a.getAttribute('data-price')),y=num(b.getAttribute('data-price'));return (x==null?1e9:x)-(y==null?1e9:y);});else ord.sort(function(a,b){return a.getAttribute('data-i')-b.getAttribute('data-i');});ord.forEach(function(c){list.appendChild(c);});
    if(n)n.textContent=vis;if(em)em.hidden=vis>0;}
  w.querySelectorAll('.grp').forEach(function(g){g.addEventListener('click',function(e){var b=e.target.closest('.op');if(!b)return;g.querySelectorAll('.op').forEach(function(x){x.classList.toggle('on',x===b);});
    if(b.hasAttribute('data-sort'))sort=b.getAttribute('data-sort');else{sel[g.getAttribute('data-g')]=b.getAttribute('data-v');DL({event:'finder_filter',filtro:b.getAttribute('data-v')||'todas'});}apply();});});apply();});
document.querySelectorAll('[data-bundle]').forEach(function(w){var unit=w.getAttribute('data-unit')||'';var base=num(w.getAttribute('data-base'));var boxes=[].slice.call(w.querySelectorAll('input[type=checkbox][data-n]'));
  function upd(ev){var names=[],tot=base||0,known=true,any=false;boxes.forEach(function(b){if(!b.checked)return;any=true;names.push(b.getAttribute('data-n'));var p=num(b.getAttribute('data-p'));if(p==null)known=false;else tot+=p;});
    var ul=w.querySelector('[data-bundle-list]');if(ul)ul.innerHTML=names.length?names.map(function(x){var li=document.createElement('li');li.textContent=x;return li.outerHTML;}).join(''):'<li>Elige al menos una opción</li>';
    var s=w.querySelector('[data-bundle-sum]');var txt=!any?'—':known?fmt(tot)+' '+unit:'A medida';if(s)s.textContent=txt;
    var f=w.querySelector('[data-bundle-field]');if(f)f.value=names.join(' + ');var t=w.querySelector('[data-bundle-total]');if(t)t.value=known&&any?fmt(tot)+' '+unit:'';
    var c=w.querySelector('[data-bundle-cta]');if(c){c.setAttribute('data-plan',names.join(' + '));c.setAttribute('data-price',known&&any?fmt(tot)+' '+unit:'');}
    var wa=w.querySelector('[data-bundle-wa]');if(wa){var base0=wa.getAttribute('data-base')||wa.getAttribute('href');wa.setAttribute('data-base',base0);wa.setAttribute('href',base0+'?text='+encodeURIComponent('Hola, me interesa este pack: '+names.join(' + ')+(known&&any?' ('+fmt(tot)+' '+unit+')':'')));}
    if(ev)DL({event:'bundle_change',pack:names.join(' + ')});}
  boxes.forEach(function(b){b.addEventListener('change',upd);});upd();});
document.querySelectorAll('[data-booking]').forEach(function(w){var nd=parseInt(w.getAttribute('data-days'),10)||6,sat=w.getAttribute('data-sat')==='1';var box=w.querySelector('[data-bk-days]');var d=new Date();d.setHours(12,0,0,0);var out=[];var guard=0;
  while(out.length<nd&&guard++<30){d.setDate(d.getDate()+1);var wd=d.getDay();if(wd===0||(wd===6&&!sat))continue;out.push(new Date(d));}
  var iso=function(x){return x.getFullYear()+'-'+('0'+(x.getMonth()+1)).slice(-2)+'-'+('0'+x.getDate()).slice(-2);};
  box.innerHTML=out.map(function(x,i){return '<button type="button" class="dx-bk-d" data-day="'+iso(x)+'" aria-pressed="false"><small>'+(Math.round((x-new Date(new Date().setHours(12,0,0,0)))/864e5)===1?'mañana':x.toLocaleDateString('es-ES',{weekday:'short'}))+'</small><b>'+x.getDate()+'</b><small>'+x.toLocaleDateString('es-ES',{month:'short'})+'</small></button>';}).join('');
  var fd=w.querySelector('[data-bk-day]'),fs=w.querySelector('[data-bk-slot]'),info=w.querySelector('[data-bk-sel]');
  function txt(){var dd=w.querySelector('.dx-bk-d[aria-pressed="true"]'),ss=w.querySelector('.dx-bk-s[aria-pressed="true"]');if(info)info.innerHTML=dd&&ss?'Te llamamos el <b>'+new Date(dd.getAttribute('data-day')+'T12:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})+'</b>, en la franja <b>'+ss.getAttribute('data-slot')+'</b>.':'Elige día y hora.';}
  w.addEventListener('click',function(e){var b=e.target.closest('.dx-bk-d,.dx-bk-s');if(!b)return;var grp=b.classList.contains('dx-bk-d')?'.dx-bk-d':'.dx-bk-s';w.querySelectorAll(grp).forEach(function(x){x.setAttribute('aria-pressed',x===b?'true':'false');});
    if(grp==='.dx-bk-d'&&fd)fd.value=b.getAttribute('data-day');if(grp==='.dx-bk-s'&&fs)fs.value=b.getAttribute('data-slot');txt();DL({event:'booking_pick',tipo:grp==='.dx-bk-d'?'dia':'hora'});});
  var f=w.querySelector('form');if(f)f.addEventListener('submit',function(e){if(!fd.value||!fs.value){e.preventDefault();e.stopImmediatePropagation();if(info)info.innerHTML='<b style="color:#d93025">Elige día y hora para reservar.</b>';}},true);txt();});
function vsrc(u){var m=u.match(/(?:youtube\\.com\\/(?:watch\\?v=|shorts\\/|embed\\/)|youtu\\.be\\/)([\\w-]{11})/);if(m)return {f:'https://www.youtube-nocookie.com/embed/'+m[1]+'?autoplay=1&rel=0&cc_load_policy=1',w:/shorts/.test(u)?0:1};
  m=u.match(/vimeo\\.com\\/(\\d+)/);if(m)return {f:'https://player.vimeo.com/video/'+m[1]+'?autoplay=1&texttrack=es',w:1};if(/\\.(mp4|webm)(\\?|$)/i.test(u))return {v:u,w:0};return null;}
document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.dx-vt-p');if(!b)return;var u=b.getAttribute('data-video')||'';var s=vsrc(u);if(!s)return;e.preventDefault();
  var o=document.createElement('div');o.className='nc-vbox'+(s.w?' wide':'');o.setAttribute('role','dialog');o.setAttribute('aria-modal','true');
  o.innerHTML='<div><button type="button" aria-label="Cerrar">×</button>'+(s.f?'<iframe src="'+s.f+'" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen title="Vídeo"></iframe>':'<video src="'+s.v+'" controls autoplay playsinline></video>')+'</div>';
  function close(){o.remove();document.removeEventListener('keydown',k);}function k(ev){if(ev.key==='Escape')close();}o.addEventListener('click',function(ev){if(ev.target===o||ev.target.closest('button'))close();});document.addEventListener('keydown',k);document.body.appendChild(o);DL({event:'video_play',video:u});});
})();`;
(function(){const _bd=buildDoc;buildDoc=function(forExport){let h=_bd.apply(this,arguments);if(!state.sections.some(s=>!s.hidden&&NC_PLUS_TYPES.test(s.type)))return h;
  return h.replace("</head>",`<style>${ncPlusCSS()}</style></head>`).replace(/<\/body>(?![\s\S]*<\/body>)/,`<script>${NC_PLUS_JS}<\/script></body>`);};})();
