/* ---------- BLOQUES PARA CASOS DE USO (v3.9) ----------
   Quiz de varios pasos, advertorial, storytelling, guía descargable, zona de servicio,
   profesional, resumen de valoraciones y página de gracias.
   Construidos con piezas de la familia A (heredan el estilo de diseño). Sin datos inventados. */
Object.assign(LIB,{
dx_quiz:{label:"✚ Quiz de varios pasos",ico:"⋯",cat:"Extras CRO",raw:true,
  def:()=>({kicker:"Estudio gratuito",title:"Encuentra la opción que encaja contigo",sub:"Responde {{N}} preguntas rápidas y te llamamos con una propuesta a medida.",steps:"¿Qué quieres proteger?|Casa,Piso,Negocio,Segunda vivienda\n¿Tienes alarma ahora?|Sí,No\n¿Cuándo la necesitas?|Cuanto antes,Este mes,Solo estoy mirando",final:"Último paso: ¿a qué teléfono te llamamos?",btn:"Ver mi propuesta",safe:"Tu número solo se usa para llamarte. Sin spam."}),
  fields:[{k:"kicker",l:"Antetítulo"},{k:"title",l:"Título"},{k:"sub",l:"Texto"},{k:"steps",l:"Preguntas (pregunta|opción,opción,… una por línea)",t:"ta"},{k:"final",l:"Texto del último paso"},{k:"btn",l:"Botón final"},{k:"safe",l:"Texto de privacidad"}],
  render:p=>{const S=v4L(p.steps).map(l=>{const c=v4C(l);return {q:c[0],o:String(c[1]||"").split(",").map(x=>x.trim()).filter(Boolean)};}).filter(s=>s.q);const n=S.length;
    return `<section class="da da-sec soft dx-quizs"><div class="container" style="max-width:760px"><div class="text-center mb-4"><span class="da-eyebrow">${esc(p.kicker)}</span><h2 class="da-h2 mt-2">${esc(p.title)}</h2><p class="da-muted">${esc(String(p.sub||"").replace("{{N}}",n))}</p></div>
    <div class="da-card dx-quiz" id="form" data-live data-quiz><div class="dx-qbar"><i data-quiz-bar></i></div>
    ${S.map((s,i)=>`<div data-step${i?' style="display:none"':''}><div class="dx-qn">Pregunta ${i+1} de ${n}</div><h3 class="dx-qq">${esc(s.q)}</h3><div class="dx-opts">${s.o.map(o=>{const e=ncSplitEmoji(o);return `<button type="button" class="dx-opt" data-opt="${esc(e.text||o)}" data-q="${esc(s.q)}">${e.ico?ncIco(e.ico):''}<span>${esc(e.text||o)}</span>${ncIco("chevron-right","go")}</button>`;}).join("")}</div>${i?`<button type="button" class="dx-back" data-quiz-back>${vt("back")}</button>`:""}</div>`).join("")}
    <div data-step style="display:none"><div class="dx-qn">${n+1} de ${n+1}</div><h3 class="dx-qq">${esc(p.final)}</h3>${v4PhoneForm({btn:p.btn,btnCls:"da-go",arrow:true})}<button type="button" class="dx-back" data-quiz-back>${vt("back")}</button></div>
    <p class="dx-note text-center">${ncIco("lock")} ${esc(p.safe)}</p></div></div></section>`;}},
dx_article:{label:"✚ Advertorial (artículo)",ico:"¶",cat:"Extras CRO",raw:true,
  def:()=>({label:"Contenido patrocinado",kicker:"Hogar",headline:"{{TITULAR_DEL_ARTICULO}}",standfirst:"{{ENTRADILLA}}",byline:"Por {{AUTOR}} · {{FECHA}}",img:"",imgAlt:"",body:"{{PARRAFO_1}}\n\n## {{SUBTITULO}}\n\n{{PARRAFO_2}}\n\n> {{CITA_DESTACADA}}\n\n{{PARRAFO_3}}\n\n[CTA]\n\n{{PARRAFO_4}}",ctaTitle:"¿Quieres saber cuánto pagarías tú?",ctaBtn:"Consultar sin compromiso",act:"global"}),
  fields:[{k:"label",l:"Etiqueta de publicidad (obligatoria)"},{k:"kicker",l:"Sección"},{k:"headline",l:"Titular"},{k:"standfirst",l:"Entradilla",t:"ta"},{k:"byline",l:"Firma"},{k:"img",l:"Foto principal",t:"photo"},{k:"imgAlt",l:"Texto alternativo"},{k:"body",l:"Cuerpo (párrafos separados por línea en blanco · ## subtítulo · > cita · [CTA] caja de conversión)",t:"ta"},{k:"ctaTitle",l:"Caja CTA: título"},{k:"ctaBtn",l:"Caja CTA: botón"},V4_ACTF],
  render:p=>{const box=`<aside class="da-card dx-acta"><b>${esc(p.ctaTitle)}</b><a href="#form" data-cta="form"${v4ActA(p)} class="da-btn pri">${esc(p.ctaBtn)} ${I_GO()}</a></aside>`;
    const body=String(p.body||"").split(/\n\s*\n/).map(b=>b.trim()).filter(Boolean).map(b=>b==="[CTA]"?box:/^## /.test(b)?`<h2>${esc(b.slice(3))}</h2>`:/^> /.test(b)?`<blockquote>${esc(b.slice(2))}</blockquote>`:`<p>${esc(b)}</p>`).join("");
    return `<article class="da da-sec dx-art"><div class="container" style="max-width:760px"><div class="dx-adlabel">${esc(p.label||"Contenido patrocinado")}</div><span class="da-eyebrow">${esc(p.kicker)}</span>
    <h1 class="dx-ah">${esc(p.headline)}</h1><p class="dx-asf">${esc(p.standfirst)}</p><div class="dx-aby">${esc(p.byline)}</div>
    ${p.img?`<figure class="dx-afig"><img src="${esc(p.img)}" alt="${esc(p.imgAlt||'')}" fetchpriority="high"></figure>`:""}<div class="dx-abody">${body}</div></div></article>`;}},
dx_story:{label:"✚ Historia en filas",ico:"≋",cat:"Extras CRO",raw:true,
  def:()=>({title:"{{TITULO_HISTORIA}}",rows:"house|El problema|{{DESCRIPCION_PROBLEMA}}\nlightbulb|La solución|{{DESCRIPCION_SOLUCION}}\ncircle-check|El resultado|{{RESULTADO_REAL}}"}),
  fields:[{k:"title",l:"Título"},{k:"rows",l:"Filas (icono|título|texto)",t:"ta"}],
  render:p=>`<section class="da da-sec"><div class="container"><h2 class="da-h2 mb-5" style="max-width:720px">${esc(p.title)}</h2><div class="dx-story">${v4L(p.rows).map((l,i)=>{const c=v4C(l);return `<div class="r ${i%2?'rev':''}"><div class="v"><span>${ncIconOrText(c[0])}</span><em>${String(i+1).padStart(2,"0")}</em></div><div class="t"><h3>${esc(c[1]||'')}</h3><p>${esc(c[2]||'')}</p></div></div>`;}).join("")}</div></div></section>`},
dx_leadmag:{label:"✚ Guía descargable",ico:"▤",cat:"Extras CRO",raw:true,
  def:()=>({kicker:"Guía gratuita",title:"{{TITULO_GUIA}}",sub:"Te la enviamos por email al momento.",bullets:"{{PUNTO_1}}\n{{PUNTO_2}}\n{{PUNTO_3}}",cover:"{{TITULO_GUIA}}",btn:"Enviarme la guía",phone:true}),
  fields:[{k:"kicker",l:"Antetítulo"},{k:"title",l:"Título"},{k:"sub",l:"Texto"},{k:"bullets",l:"Qué incluye (una por línea)",t:"ta"},{k:"cover",l:"Título en la portada"},{k:"btn",l:"Botón"}],
  render:p=>`<section class="da da-sec soft"><div class="container"><div class="row g-4 g-lg-5 align-items-center"><div class="col-lg-5 d-flex justify-content-center"><div class="dx-book" aria-hidden="true"><span class="k">${esc(p.kicker)}</span><b>${esc(p.cover)}</b><i></i></div></div>
    <div class="col-lg-7"><span class="da-eyebrow">${esc(p.kicker)}</span><h2 class="da-h2 mt-2">${esc(p.title)}</h2><p class="da-muted">${esc(p.sub)}</p>${v4Checks(p.bullets,"da-checks dx-lmck")}
    <div class="da-card mt-4" id="form"><form data-callback action="${v4Act()}" method="post" class="dx-lmf"><input required name="nombre" class="form-control" placeholder="Nombre"><input required name="email" type="email" class="form-control" placeholder="Email"><input name="telefono" type="tel" class="form-control" placeholder="${esc(vt("phone"))} (opcional)"><button type="submit" class="da-go">${esc(p.btn)} ${I_GO()}</button></form></div></div></div></div></section>`},
dx_area:{label:"✚ Zona de servicio (local)",ico:"⌂",cat:"Extras CRO",raw:true,
  def:()=>({title:"Instaladores en tu zona",sub:"{{TEXTO_ZONA}}",cities:"{{CIUDAD_1}}\n{{CIUDAD_2}}\n{{CIUDAD_3}}\n{{CIUDAD_4}}\n{{CIUDAD_5}}\n{{CIUDAD_6}}",hours:"{{HORARIO}}",cardTitle:"Habla con alguien de tu zona"}),
  fields:[{k:"title",l:"Título"},{k:"sub",l:"Texto"},{k:"cities",l:"Zonas / ciudades (una por línea, reales)",t:"ta"},{k:"hours",l:"Horario"},{k:"cardTitle",l:"Título de la tarjeta"}],
  render:p=>`<section class="da da-sec"><div class="container"><div class="row g-4 g-lg-5 align-items-start"><div class="col-lg-7"><span class="da-eyebrow">${ncIco("map-pin")} Zona de servicio</span><h2 class="da-h2 mt-2">${esc(p.title)}</h2><p class="da-muted">${esc(p.sub)}</p>
    <ul class="dx-cities">${v4L(p.cities).map(c=>`<li>${ncIco("map-pin")}${esc(c)}</li>`).join("")}</ul></div>
    <div class="col-lg-5"><div class="da-card dx-areac"><h3>${esc(p.cardTitle)}</h3>${v4Tel()} class="dx-bigtel">${ncIco("phone")} ${esc(telText())}</a><div class="dx-hours">${ncIco("clock")} ${esc(p.hours)}</div><div class="da-or">${vt("orWeCall")}</div>${v4PhoneForm({btn:vt("weCall"),btnCls:"da-go"})}</div></div></div></div></section>`},
dx_pro:{label:"✚ Profesional / quién te atiende",ico:"☺",cat:"Extras CRO",raw:true,
  def:()=>({kicker:"Quién lleva tu caso",name:"{{NOMBRE_PROFESIONAL}}",role:"{{ESPECIALIDAD}}",cred:"{{NUM_COLEGIADO_O_ACREDITACION}}",bio:"{{BIO_REAL}}",points:"{{AÑOS}} años de experiencia\n{{DATO_REAL}}\nPrimera consulta sin compromiso",img:""}),
  fields:[{k:"kicker",l:"Antetítulo"},{k:"name",l:"Nombre (real)"},{k:"role",l:"Especialidad"},{k:"cred",l:"Colegiado / acreditación (real)"},{k:"bio",l:"Bio",t:"ta"},{k:"points",l:"Puntos (uno por línea)",t:"ta"},{k:"img",l:"Foto",t:"photo"}],
  render:p=>{const ini=String(p.name||"").replace(/\{\{|\}\}/g,"").split(/[\s_]+/).filter(Boolean).slice(0,2).map(w=>w[0]).join("")||"·";
    return `<section class="da da-sec"><div class="container" style="max-width:1000px"><div class="dx-pro"><div class="ph">${p.img?`<img src="${esc(p.img)}" alt="${esc(p.name)}" loading="lazy">`:`<span>${esc(ini)}</span>`}</div>
    <div><span class="da-eyebrow">${esc(p.kicker)}</span><h2 class="da-h2 mt-2 mb-1">${esc(p.name)}</h2><div class="dx-prole">${esc(p.role)} · <span>${esc(p.cred)}</span></div><p class="da-muted mt-3">${esc(p.bio)}</p>${v4Checks(p.points,"da-checks")}</div></div></div></section>`;}},
dx_rating:{label:"✚ Resumen de valoraciones",ico:"★",cat:"Extras CRO",raw:true,
  def:()=>({score:"{{VALORACION}}",count:"{{N_OPINIONES}}",platform:"{{PLATAFORMA}}",title:"Lo que opinan quienes ya se han cambiado",note:"Valoración media en {{PLATAFORMA}}. Opiniones verificadas por la plataforma."}),
  fields:[{k:"title",l:"Título"},{k:"score",l:"Nota (real)"},{k:"count",l:"Nº de opiniones (real)"},{k:"platform",l:"Plataforma"},{k:"note",l:"Nota"}],
  render:p=>`<section class="da dx-rate"><div class="container"><div class="dx-rategrid"><div class="sc"><b>${esc(p.score)}</b><span class="st">★★★★★</span></div><div><h2 class="da-h2">${esc(p.title)}</h2><p class="da-muted mb-0">${esc(p.count)} opiniones en <b>${esc(p.platform)}</b>. ${esc(String(p.note||"").replace(/Valoración media en \{\{PLATAFORMA\}\}\. ?/,""))}</p></div></div></div></section>`},
dx_thanks:{label:"✚ Página de gracias",ico:"✓",cat:"Extras CRO",raw:true,
  def:()=>({title:"¡Recibido! Te llamamos en breve",sub:"Un asesor te llamará desde el {{TELEFONO}} en {{TIEMPO_RESPUESTA}}. Ten el móvil a mano.",steps:"Revisamos tu solicitud|Con los datos que nos has dejado.\nTe llamamos|Te explicamos opciones y precio final.\nDecides tú|Sin compromiso y sin prisas.",callTxt:"¿No quieres esperar? Llama ahora",waTxt:"O escríbenos por WhatsApp"}),
  fields:[{k:"title",l:"Título"},{k:"sub",l:"Texto",t:"ta"},{k:"steps",l:"Qué pasa ahora (título|texto)",t:"ta"},{k:"callTxt",l:"Texto de llamada"},{k:"waTxt",l:"Texto de WhatsApp"}],
  render:p=>`<section class="da da-hero dx-thx" data-nc-thanks><div class="container" style="max-width:760px"><span class="dx-ok">${ncIco("circle-check")}</span><h1 class="da-h1">${esc(p.title)}</h1><p class="da-sub mx-auto">${esc(String(p.sub||"").replace("{{TELEFONO}}",telText()))}</p>
    <ol class="dx-tl mt-4 text-start">${v4L(p.steps).map((l,i)=>{const c=v4C(l);return `<li><span class="n">${i+1}</span><div><h3>${esc(c[0])}</h3><p>${esc(c[1]||'')}</p></div></li>`;}).join("")}</ol>
    <div class="dx-thxc"><span>${esc(p.callTxt)}</span>${v4Tel()} class="da-btn pri">${ncIco("phone")} ${esc(telText())}</a>${v4Wa()} class="da-btn sec">${ncIco("message-circle")} ${esc(p.waTxt)}</a></div></div></section>`}
});
(function(){const X=["dx_quiz","dx_article","dx_story","dx_leadmag","dx_area","dx_pro","dx_rating","dx_thanks"];let i=ORDER.indexOf("dx_wa");if(i<0)i=ORDER.length;else i++;ORDER.splice(i,0,...X);})();
function ncUCCSS(){if(!state.sections.some(s=>!s.hidden&&/^dx_(quiz|article|story|leadmag|area|pro|rating|thanks)$/.test(s.type)))return "";return `
.dx-quiz{padding:30px}.dx-qbar{height:5px;border-radius:5px;background:var(--dline);overflow:hidden;margin-bottom:22px}.dx-qbar i{display:block;height:100%;width:0;min-width:12%;background:var(--bp);transition:width .35s}
.dx-qn{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--bpt)}.dx-qq{font:var(--lk-hw,800) 24px/1.2 var(--fhead);margin:8px 0 18px;color:var(--ink0)}
.dx-opts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.dx-opt{display:flex;align-items:center;gap:12px;text-align:left;border:1.5px solid var(--dline);background:#fff;color:var(--ink0);border-radius:12px;padding:15px 16px;font-weight:600;font-size:15.5px;transition:border-color .15s,transform .15s}
.dx-opt span{flex:1}.dx-opt .nci{color:var(--bpt)}.dx-opt .go{opacity:.35}.dx-opt:hover,.dx-opt.on{border-color:var(--bp);transform:translateY(-1px)}.dx-opt.on{background:color-mix(in srgb,var(--bp) 7%,#fff)}
.dx-back{background:none;border:0;color:var(--bmuted);font-size:13px;margin-top:14px;padding:0}.dx-quiz .form-control{min-height:52px;margin-bottom:8px}.dx-quiz .da-go{width:100%}
.dx-art{padding-top:48px}.dx-adlabel{display:inline-block;font:700 11px/1 var(--fbody);letter-spacing:.14em;text-transform:uppercase;color:var(--bmuted);border:1px solid var(--dline);padding:6px 9px;border-radius:3px;margin-bottom:22px}
.dx-ah{font:var(--lk-hw,800) clamp(32px,4.4vw,52px)/1.05 var(--fhead);letter-spacing:-.025em;margin:12px 0 16px;color:var(--bink)}.dx-asf{font-size:20px;line-height:1.5;color:var(--bmuted)}.dx-aby{font-size:13.5px;color:var(--bmuted);border-top:1px solid var(--dline);border-bottom:1px solid var(--dline);padding:10px 0;margin:22px 0}
.dx-afig{margin:0 0 26px}.dx-afig img{width:100%;border-radius:6px;display:block}.dx-abody p{font-size:18px;line-height:1.7;color:var(--bink);margin:0 0 20px}.dx-abody h2{font:700 26px/1.2 var(--fhead);margin:34px 0 14px;color:var(--bink)}
.dx-abody blockquote{font:500 24px/1.4 var(--fhead);margin:30px 0;padding:0 0 0 22px;border-left:4px solid var(--bp);color:var(--bink)}.dx-acta{display:flex;flex-wrap:wrap;gap:14px;align-items:center;justify-content:space-between;margin:28px 0;padding:22px 24px}.dx-acta b{font:800 19px/1.3 var(--fhead);color:var(--ink0);flex:1 1 260px}
.dx-story .r{display:grid;grid-template-columns:1fr 1.3fr;gap:48px;align-items:center;padding:34px 0;border-top:1px solid var(--dline)}.dx-story .r.rev .v{order:2}
.dx-story .v{position:relative;aspect-ratio:4/3;border-radius:var(--visr,20px);background:var(--visbg,color-mix(in srgb,var(--bp) 9%,var(--bsoft)));display:grid;place-items:center;overflow:hidden}.dx-story .v span{font-size:clamp(56px,8vw,110px);color:var(--bpt);line-height:1}.dx-story .v em{position:absolute;left:18px;top:14px;font:700 13px var(--fmono,var(--fhead));font-style:normal;color:var(--bmuted)}
.dx-story h3{font:var(--lk-hw,800) clamp(24px,2.6vw,34px)/1.1 var(--fhead);margin:0 0 12px;color:var(--bink)}.dx-story p{font-size:17px;color:var(--bmuted);margin:0}
.dx-book{width:240px;aspect-ratio:3/4;border-radius:4px 12px 12px 4px;background:linear-gradient(90deg,color-mix(in srgb,#000 22%,var(--bp)) 0 14px,var(--bp) 14px);color:var(--btntext,#fff);padding:30px 24px 24px 38px;display:flex;flex-direction:column;box-shadow:18px 22px 40px -18px rgba(0,0,0,.45);transform:rotate(-4deg);position:relative}
.dx-book .k{font-size:11px;letter-spacing:.14em;text-transform:uppercase;opacity:.8}.dx-book b{font:800 26px/1.1 var(--fhead);margin-top:14px;overflow-wrap:anywhere}.dx-book i{margin-top:auto;height:6px;width:56px;border-radius:3px;background:currentColor;opacity:.6}
.dx-lmck{flex-direction:column;gap:8px!important}.dx-lmf{display:grid;grid-template-columns:1fr 1fr;gap:8px}.dx-lmf .form-control{margin:0!important;min-height:50px}.dx-lmf input[type=tel],.dx-lmf .da-go,.dx-lmf .nc-legal,.dx-lmf .nc-legal-info{grid-column:1/-1}
.dx-cities{list-style:none;padding:0;margin:22px 0 0;display:flex;flex-wrap:wrap;gap:8px}.dx-cities li{display:inline-flex;gap:6px;align-items:center;border:1px solid var(--dline);border-radius:99px;padding:8px 14px;font-weight:600;font-size:14.5px;color:var(--bink);background:#fff}.dx-cities .nci{color:var(--bpt)}
.dx-areac h3{font:800 20px var(--fhead);margin:0 0 10px;color:var(--ink0)}.dx-bigtel{display:flex;gap:10px;align-items:center;font:800 28px var(--fhead);color:var(--ink0);text-decoration:none;margin:4px 0 6px}.dx-bigtel .nci{color:var(--bp)}.dx-hours{font-size:14px;color:#6b6472;display:flex;gap:6px;align-items:center}
.dx-pro{display:grid;grid-template-columns:260px 1fr;gap:44px;align-items:center}.dx-pro .ph{aspect-ratio:4/5;border-radius:var(--visr,20px);overflow:hidden;background:var(--visbg,color-mix(in srgb,var(--bp) 12%,var(--bsoft)));display:grid;place-items:center}
.dx-pro .ph img{width:100%;height:100%;object-fit:cover}.dx-pro .ph span{font:800 72px var(--fhead);color:var(--bpt)}.dx-prole{font-weight:700;color:var(--bpt)}.dx-prole span{color:var(--bmuted);font-weight:500}.dx-pro .da-checks{flex-direction:column;gap:8px}
.dx-rate{padding:56px 0;background:var(--bsoft)}.dx-rategrid{display:grid;grid-template-columns:auto minmax(0,1fr);gap:40px;align-items:center}.dx-rate .sc{text-align:center}.dx-rate .sc{min-width:0;max-width:42vw}.dx-rate .sc b{overflow-wrap:anywhere;display:block;font:800 clamp(56px,7vw,96px)/1 var(--fhead);letter-spacing:-.04em;color:var(--bink)}.dx-rate .st{color:#E3A008;letter-spacing:3px;font-size:20px}
.dx-thx{text-align:center;padding:70px 0}.dx-ok{display:inline-grid;place-items:center;width:84px;height:84px;border-radius:50%;background:color-mix(in srgb,#16a34a 14%,#fff);color:#16a34a;font-size:44px;margin-bottom:16px}
.dx-thx .dx-tl{max-width:520px;margin-left:auto;margin-right:auto}.dx-thxc{display:flex;flex-direction:column;align-items:center;gap:10px;margin-top:10px}.dx-thxc span{color:var(--bmuted);font-size:14px}.dx-thxc .da-btn{min-width:280px;justify-content:center}
@media (max-width:767px){.dx-opts{grid-template-columns:1fr}.dx-quiz{padding:22px}.dx-qq{font-size:21px}.dx-story .r{grid-template-columns:1fr;gap:18px;padding:24px 0}.dx-story .r.rev .v{order:0}.dx-story .v{aspect-ratio:16/9}
 .dx-book{width:190px}.dx-lmf{grid-template-columns:1fr}.dx-pro{grid-template-columns:1fr;gap:22px}.dx-pro .ph{max-width:220px}.dx-rategrid{grid-template-columns:minmax(0,1fr);gap:14px;text-align:center}.dx-rate .sc b{font-size:clamp(40px,12vw,56px)}
 .dx-abody p{font-size:17px}.dx-asf{font-size:18px}.dx-thxc .da-btn{min-width:0;width:100%}}`;}
