/* ---------- v4.6 · SECTORES NUEVOS + PLANTILLAS ----------
   Sectores: Agua (filtración), Reformas, Coche (seguro), Teleasistencia y Empresas (fibra y telefonía B2B).
   Cada sector trae copy de hero, cifras, ventajas, FAQ y comparativa; se generan sus plantillas Sector × canal
   y plantillas nuevas con los bloques interactivos y los estilos de Tendencias 2026.
   Precios, cifras, plazos, garantías, nombres y opiniones: siempre {{PLACEHOLDER}}. */
Object.assign(V4_SECTORS,{
  "Agua":{dir:"A",hero:{eyebrow:"Análisis de agua gratuito",headline:"Agua de calidad",highlight:"directa del grifo",sub:"Analizamos el agua de tu casa y te proponemos el equipo que de verdad necesitas. Sin compromiso.",price:"{{PRECIO}}",priceUnit:"€/mes",priceNote:"{{CONDICIONES}}",checks:"Análisis gratis en casa\nInstalación incluida\nMantenimiento {{MANTENIMIENTO}}",cardTitle:"Pide tu análisis gratuito",cardSub:"Déjanos tu teléfono y te llamamos para concertar la visita.",cardBtn:"Quiero el análisis"},
    trust:"{{VALORACION}}★|valoración\n{{CLIENTES}}|hogares\n{{PLAZO}}|instalación\n{{GARANTIA}}|garantía",
    plans:[{name:"Ósmosis inversa",price:"{{PRECIO_1}}",unit:"€/mes",feats:"Agua filtrada en la cocina\nInstalación incluida\nMantenimiento {{MANTENIMIENTO}}",tag:"",cta:"Lo quiero"},{name:"Descalcificador",price:"{{PRECIO_2}}",unit:"€/mes",feats:"Menos cal en toda la casa\nCuida tus electrodomésticos\nInstalación incluida",tag:"",cta:"Lo quiero"},{name:"Pack completo",price:"{{PRECIO_3}}",unit:"€/mes",feats:"Ósmosis + descalcificador\nMantenimiento incluido\nAnálisis anual",tag:"La más elegida",cta:"Lo quiero"}],
    benefits:"💧|Agua más rica|Sin olor ni sabor a cloro.\n🧴|Adiós a la cal|En grifos, mamparas y electrodomésticos.\n♻️|Menos plástico|Deja de comprar garrafas.\n🛠️|Mantenimiento|Nos ocupamos de filtros y revisiones.",
    faq:"¿Qué incluye el análisis del agua?|{{RESPUESTA}}\n¿Cada cuánto se cambian los filtros?|{{RESPUESTA}}\n¿Hay permanencia?|{{RESPUESTA}}\n¿Cuánto tarda la instalación?|{{RESPUESTA}}"},
  "Reformas":{dir:"B",hero:{kicker:"Reformas con precio cerrado",headline:"Tu reforma, con presupuesto cerrado",italic:"y fecha de entrega",sub:"Visitamos tu casa, te damos un presupuesto detallado por partidas y una fecha de entrega por escrito.",question:"¿Qué quieres reformar?",options:"🛁 Baño|🍳 Cocina|🏠 Integral|🪟 Ventanas",formTitle:"Presupuesto sin compromiso"},
    compare:{title:"Qué incluye tu presupuesto",head:"Concepto|Con nosotros|Sin empresa",rows:"Presupuesto por partidas|✓ Por escrito|A veces\nFecha de entrega|✓ En contrato|✗ No\nGestión de licencias|✓ Incluida|Por tu cuenta\nGarantía de la obra|{{GARANTIA}}|{{GARANTIA_OTROS}}"},
    faq:"¿La visita tiene coste?|{{RESPUESTA}}\n¿Cuánto tarda una reforma de baño?|{{RESPUESTA}}\n¿Os encargáis de la licencia?|{{RESPUESTA}}\n¿Cómo se paga?|{{RESPUESTA}}"},
  "Coche":{dir:"A",hero:{eyebrow:"Seguro de coche",headline:"Tu seguro de coche",highlight:"pagando menos",sub:"Comparamos coberturas y precio con tu póliza actual en una sola llamada. Tú decides.",price:"{{PRECIO}}",priceUnit:"€/año",priceNote:"{{CONDICIONES}}",checks:"Asistencia en carretera\nTe llamamos en minutos\nSin papeleo",cardTitle:"Calcula tu precio",cardSub:"Déjanos tu teléfono y te llamamos con tu propuesta.",cardBtn:"Quiero mi precio"},
    trust:"{{VALORACION}}★|valoración\n{{CLIENTES}}|conductores\n{{AHORRO_MEDIO}}|ahorro medio\n24 h|asistencia",
    plans:[{name:"A terceros",price:"{{PRECIO_1}}",unit:"€/año",feats:"Responsabilidad civil\nAsistencia en carretera\nDefensa jurídica",tag:"",cta:"Lo quiero"},{name:"Terceros ampliado",price:"{{PRECIO_2}}",unit:"€/año",feats:"Todo lo de terceros\nLunas, robo e incendio\nVehículo de sustitución {{CONDICION}}",tag:"La más elegida",cta:"Lo quiero"},{name:"Todo riesgo con franquicia",price:"{{PRECIO_3}}",unit:"€/año",feats:"Daños propios\nFranquicia de {{FRANQUICIA}}\nTaller a elegir {{CONDICION}}",tag:"",cta:"Lo quiero"}],
    benefits:"🚗|Asistencia 24 h|Grúa {{CONDICIONES_GRUA}}.\n📞|Parte por teléfono|Te acompañamos en el siniestro.\n💶|Precio claro|Sin sorpresas en la renovación.\n🔧|Talleres|{{RED_TALLERES}}.",
    faq:"¿Puedo cambiar de seguro antes de que venza?|{{RESPUESTA}}\n¿Qué necesito para calcular el precio?|{{RESPUESTA}}\n¿Cómo doy un parte?|{{RESPUESTA}}\n¿Puedo fraccionar el pago?|{{RESPUESTA}}"},
  "Teleasistencia":{dir:"B",hero:{kicker:"Teleasistencia",headline:"Que tus mayores estén acompañados",italic:"las 24 horas",sub:"Un botón para pedir ayuda en cualquier momento, en casa o fuera. Te lo explicamos sin compromiso.",question:"¿Para quién es?",options:"🙋 Para mí|👵 Para un familiar",formTitle:"Te llamamos y te lo explicamos"},
    compare:{title:"Qué incluye",head:"Servicio|Teleasistencia|Sin servicio",rows:"Botón de ayuda 24 h|✓ Sí|✗ No\nAviso a la familia|✓ Inmediato|✗ No\nDetector de caídas|{{CONDICION}}|✗ No\nLlamadas de seguimiento|✓ Incluidas|✗ No"},
    faq:"¿Funciona fuera de casa?|{{RESPUESTA}}\n¿Qué pasa si pulso el botón sin querer?|{{RESPUESTA}}\n¿Hay permanencia?|{{RESPUESTA}}\n¿Cuánto tarda la instalación?|{{RESPUESTA}}"},
  "Empresas":{dir:"A",hero:{eyebrow:"Para empresas y autónomos",headline:"Fibra y telefonía",highlight:"para tu negocio",sub:"Te decimos qué necesita tu empresa y cuánto cuesta antes de firmar nada.",price:"{{PRECIO}}",priceUnit:"€/mes + IVA",priceNote:"{{CONDICIONES}}",checks:"IP fija opcional\nCentralita en la nube\nUn gestor para tu cuenta",cardTitle:"Te llama un gestor",cardSub:"Déjanos tu teléfono y te llamamos en horario de oficina.",cardBtn:"Que me llamen"},
    trust:"{{EMPRESAS}}|empresas\n{{SLA}}|disponibilidad\n{{TIEMPO_RESPUESTA}}|respuesta\n1|gestor dedicado",
    plans:null,benefits:"🏢|Gestor dedicado|Un interlocutor para todo.\n📶|Respaldo 4G/5G|Si cae la fibra, sigues conectado.\n☎️|Centralita virtual|Extensiones, colas y horarios.\n🧾|Una factura|Fibra, móviles y centralita juntos.",
    faq:"¿Hay permanencia?|{{RESPUESTA}}\n¿Puedo mantener mis números?|{{RESPUESTA}}\n¿Qué pasa si cae la fibra?|{{RESPUESTA}}\n¿Cuánto tarda la instalación?|{{RESPUESTA}}"}
});
Object.assign(V4_SEC_ILLUS,{"Agua":"water","Reformas":"spark","Coche":"umbrella","Teleasistencia":"heart","Empresas":"wifi"});
Object.assign(UC_ILL,{"Agua":"water","Reformas":"spark","Coche":"umbrella","Teleasistencia":"heart","Empresas":"wifi"});
["Agua","Reformas","Coche","Teleasistencia","Empresas"].forEach(sec=>["form","call","wa"].forEach(canal=>{const S=V4_SECTORS[sec];
  v4Tpl(`${sec} · ${V4_CANAL_TXT[canal]}`,{group:"Sector",sector:sec,dir:S.dir,canal,desc:`${sec}: canal principal ${V4_CANAL_TXT[canal].toLowerCase()}, con callback siempre disponible.`},v4SectorSections(sec,canal));}));
function plTpl(name,look,sec,dir,canal,desc,secs){v4Tpl(name,{group:"Estilos",look,sector:sec,dir,canal,desc},secs);}
const PL_S=V4_SECTORS,PLH=(sec,over)=>ucHero(sec,over);
const PL_BUNDLE_TELCO="Fibra {{VELOCIDAD}}|{{PRECIO_FIBRA}}|on\nLínea móvil {{GB}}|{{PRECIO_MOVIL}}|on\nSegunda línea {{GB_2}}|{{PRECIO_LINEA_2}}|\nTV {{PAQUETE_TV}}|{{PRECIO_TV}}|\nFútbol {{PAQUETE_FUTBOL}}|{{PRECIO_FUTBOL}}|";
const PL_FINDER_COCHE={title:"Encuentra tu cobertura",sub:"Marca lo que necesitas y te enseñamos solo los seguros que encajan.",filters:"Cobertura|Terceros,Terceros ampliado,Todo riesgo\nConductor|Menor de 26,Más de 26",
  plans:PL_S.Coche.plans.map((p,i)=>Object.assign({},p,{tags:["Terceros,Menor de 26,Más de 26","Terceros ampliado,Menor de 26,Más de 26","Todo riesgo,Más de 26"][i]}))};
const PL_FINDER_B2B={title:"Encuentra el plan de tu empresa",sub:"Filtra por tamaño y lo que necesitas.",filters:"Equipo|1-5 personas,6-20 personas,Más de 20\nNecesito|Solo fibra,Fibra + centralita,Fibra + móviles",
  plans:[{name:"Fibra Empresa",price:"{{PRECIO_1}}",unit:"€/mes + IVA",feats:"{{VELOCIDAD_1}} simétricos\nIP fija opcional",tags:"1-5 personas,Solo fibra",tag:"",cta:"La quiero"},{name:"Oficina conectada",price:"{{PRECIO_2}}",unit:"€/mes + IVA",feats:"{{VELOCIDAD_2}} simétricos\nCentralita {{N_EXTENSIONES}} extensiones",tags:"6-20 personas,Fibra + centralita",tag:"La más elegida",cta:"La quiero"},{name:"Empresa total",price:"{{PRECIO_3}}",unit:"€/mes + IVA",feats:"Fibra + respaldo 4G/5G\n{{N_LINEAS}} líneas móviles",tags:"Más de 20,6-20 personas,Fibra + móviles",tag:"",cta:"Hablar con un gestor"}]};
/* ===== Sectores nuevos con bloques interactivos ===== */
plTpl("Agua · Configura tu equipo","neobanco","Agua","A","form","Filtración de agua: hero con análisis gratis, configurador de equipo con total en vivo, ventajas y FAQ.",
  [NAV("da"),PLH("Agua",{layout:"std"}),{type:"dx_seals"},{type:"dx_bundle",props:{title:"Configura tu equipo",sub:"Marca lo que quieres y te confirmamos el precio en la visita.",items:"Ósmosis inversa|{{PRECIO_OSMOSIS}}|on\nDescalcificador|{{PRECIO_DESCAL}}|\nGrifo de tres vías|{{PRECIO_GRIFO}}|\nMantenimiento anual|{{PRECIO_MANT}}|on",btn:"Quiero mi análisis gratis"}},{type:"da_benefits",props:{items:PL_S.Agua.benefits}},{type:"da_faq",props:{items:PL_S.Agua.faq}},{type:"da_cta"},FOOT("da"),STK("da")]);
plTpl("Agua · Análisis en casa","tipografico","Agua","A","form","Agua con estilo Tipográfico: titular enorme, cita para el análisis en casa y testimonios en vídeo.",
  [NAV("da"),PLH("Agua"),{type:"da_trust",props:{items:PL_S.Agua.trust}},{type:"dx_booking",props:{title:"¿Cuándo te viene bien el análisis?",sub:"Elige día y franja y te llamamos para confirmarlo."}},{type:"dx_vtestis"},{type:"da_plans",props:{plans:PL_S.Agua.plans}},{type:"da_faq",props:{items:PL_S.Agua.faq}},FOOT("da"),STK("da")]);
plTpl("Reformas · Presupuesto cerrado","tipografico","Reformas","B","form","Reformas: multipaso en el hero, pasos, comparativa, testimonios en vídeo y FAQ.",
  [NAV("db"),PLH("Reformas"),{type:"db_seals"},{type:"db_steps",props:{title:"Así trabajamos",items:"Visita sin coste|Medimos y vemos lo que quieres.\nPresupuesto por partidas|Sabrás qué pagas por cada cosa.\nObra con fecha|La fecha de entrega va en el contrato."}},{type:"db_compare",props:PL_S.Reformas.compare},{type:"dx_vtestis",props:{title:"Reformas que nos cuentan sus dueños"}},{type:"db_faq",props:{items:PL_S.Reformas.faq}},{type:"db_cta"},FOOT("db"),STK("db")]);
plTpl("Reformas · Pide visita","crudo","Reformas","A","form","Reformas con estilo Crudo: honesto y directo; reserva de visita por día y franja.",
  [NAV("da"),{type:"dx_text",props:{kicker:"Reformas",title:"Te decimos lo que cuesta tu reforma. Por escrito.",text:"Visitamos tu casa, medimos y te mandamos un presupuesto por partidas con fecha de entrega.\nSi no te encaja, no pasa nada.",btn:"",align:"left"}},{type:"dx_booking",props:{title:"Reserva la visita",sub:"Escoge día y franja. Te llamamos antes para confirmarla.",btn:"Reservar visita"}},{type:"db_compare",props:PL_S.Reformas.compare},{type:"db_faq",props:{items:PL_S.Reformas.faq}},FOOT("da"),STK("da")]);
plTpl("Coche · Compara tu seguro","neobanco","Coche","A","form","Seguro de coche: hero con precio, comparador con filtros de cobertura y conductor, garantías y FAQ.",
  [NAV("da"),PLH("Coche",{layout:"std"}),{type:"dx_seals"},{type:"dx_finder",props:PL_FINDER_COCHE},{type:"dx_vs",props:{title:"Lo que cambia con nosotros",them:"Tu seguro actual"}},{type:"da_faq",props:{items:PL_S.Coche.faq}},{type:"da_cta"},FOOT("da"),STK("da")]);
plTpl("Coche · Renueva sin sorpresas","acido","Coche","A","call","Seguro de coche con estilo Ácido: llamada como canal principal, coberturas y opiniones en vídeo.",
  [NAV("da"),PLH("Coche",{canal:"call"}),{type:"da_trust",props:{items:PL_S.Coche.trust}},{type:"da_plans",props:{plans:PL_S.Coche.plans}},{type:"dx_vtestis"},{type:"da_faq",props:{items:PL_S.Coche.faq}},FOOT("da"),STK("da","call")]);
plTpl("Teleasistencia · Para tu familia","tipografico","Teleasistencia","B","call","Teleasistencia: pensada para familiares; cita para que te lo expliquen y testimonios en vídeo.",
  [NAV("db"),PLH("Teleasistencia",{canal:"call"}),{type:"dx_booking",props:{title:"¿Cuándo te llamamos para explicártelo?",sub:"Elige día y franja. La llamada dura unos minutos.",btn:"Que me llamen ese día"}},{type:"db_compare",props:PL_S.Teleasistencia.compare},{type:"dx_vtestis",props:{title:"Familias que ya lo tienen"}},{type:"db_faq",props:{items:PL_S.Teleasistencia.faq}},FOOT("db"),STK("db","call")]);
plTpl("Empresas · Encuentra tu plan","acido","Empresas","A","form","B2B con estilo Ácido: hero de producto, cifras de servicio, comparador por tamaño de equipo y formulario en 2 pasos.",
  [NAV("da"),{type:"dx_product",props:{kicker:"Para empresas",headline:"Tu negocio, siempre conectado.",highlight:"Y con un gestor de verdad.",sub:"Fibra, móviles y centralita en una sola factura. Te decimos qué necesitas antes de firmar nada.",price:"{{PRECIO}}",priceUnit:"€/mes + IVA",illus:"wifi",cta:"Que me llame un gestor"}},{type:"dx_stats",props:{items:PR_STATS.B2B}},{type:"dx_finder",props:PL_FINDER_B2B},{type:"dx_form2"},{type:"da_faq",props:{items:PL_S.Empresas.faq}},FOOT("da"),STK("da")]);
/* ===== Estilos nuevos en sectores clave ===== */
plTpl("Ácido · Arma tu pack","acido","Telco","A","form","Telco joven: hero con precio, configurador de pack (fibra, móvil, TV, fútbol) con total en vivo y FAQ.",
  [{type:"da_topbar"},NAV("da"),PLH("Telco"),{type:"dx_bundle",props:{items:PL_BUNDLE_TELCO,title:"Arma tu pack",btn:"Quiero este pack",act:"popup"}},{type:"da_benefits",props:{items:PL_S.Telco.benefits}},{type:"da_faq",props:{items:PL_S.Telco.faq}},{type:"da_cta"},FOOT("da"),STK("da")]);
plTpl("Tipográfico · Luz con precio claro","tipografico","Energía","A","form","Energía con estilo Tipográfico: precio enorme, calculadora y tarifas sobre papel cálido.",
  [NAV("da"),PLH("Energía"),{type:"da_trust",props:{items:PL_S["Energía"].trust}},{type:"dx_calc",props:{unit:"€/mes"}},{type:"da_plans",props:{plans:PL_S["Energía"].plans}},{type:"da_faq",props:{items:PL_S["Energía"].faq}},{type:"da_cta"},FOOT("da"),STK("da")]);
plTpl("Crudo · Reclamación sin rodeos","crudo","Legal","B","form","Legal con estilo Crudo: lo que cuesta, cómo funciona y una cita para estudiar tu caso.",
  [NAV("db"),PLH("Legal"),{type:"db_compare",props:PL_S.Legal.compare},{type:"db_steps"},{type:"dx_booking",props:{title:"Reserva una llamada con un abogado",sub:"Elige día y franja. Estudiamos tu caso sin coste.",btn:"Reservar llamada"}},{type:"db_faq",props:{items:PL_S.Legal.faq}},FOOT("db"),STK("db")]);
plTpl("Crudo · Fibra sin rollos","crudo","Telco","A","form","Telco con estilo Crudo: comparador con filtros y el precio sin adornos.",
  [NAV("da"),PLH("Telco",{layout:"std"}),{type:"dx_finder"},{type:"da_benefits",props:{items:PL_S.Telco.benefits}},{type:"da_faq",props:{items:PL_S.Telco.faq}},FOOT("da"),STK("da")]);
