/* ---------- PLANTILLAS · PRODUCTO Y TECNOLOGÍA (v4.5) ----------
   Estructuras de las páginas que mejor convierten en producto premium, fintech y SaaS, cableadas a nuestros canales:
   · Vitrina   → barra de producto con compra fija + hero centrado con formulario + "lo esencial" en bento + cifras + tarifas.
   · Neobanco  → chip de confianza + garantías junto al CTA + comparativa nosotros/otros + pasos + cifras con fuente.
   · Nocturno  → B2B oscuro: hero centrado, cifras, bento, tarifas, formulario en 2 pasos.
   Precios, cifras, garantías, opiniones y nombres: siempre {{PLACEHOLDER}}. */
function prTpl(name,look,sec,dir,canal,desc,secs){v4Tpl(name,{group:"Estilos",look,sector:sec,dir,canal,desc},secs);}
const PR_S=V4_SECTORS;
const PR_TILES={
  Telco:"L|Wifi en toda la casa|Router {{MODELO_ROUTER}} incluido y técnico que te lo deja configurado.|dark\nS|{{VELOCIDAD}}|simétricos, de verdad|brand\nS|{{PLAZO}}|para tenerla instalada|light\nL|Mantienes tu número|Hacemos la portabilidad por ti, sin cortes.|light\nM|Precio final|Lo que ves es lo que pagas. IVA incluido.|light\nM|Personas, no robots|Te atiende un asesor en {{HORARIO}}.|accent",
  Alarmas:"L|Te avisamos antes que nadie|Central receptora {{HORARIO_CRA}} y aviso a emergencias.|dark\nS|{{TIEMPO_RESPUESTA}}|de respuesta media|brand\nS|App|Arma y desarma desde el móvil|light\nL|Estudio de seguridad gratis|Un experto revisa tu casa o negocio sin compromiso.|light\nM|Instalación profesional|Técnicos certificados en {{PLAZO}}.|light\nM|Mantenimiento incluido|{{CONDICIONES_MANTENIMIENTO}}|accent",
  "Energía":"L|Produce tu propia energía|Estudio de tu tejado y de tu consumo antes de proponerte nada.|dark\nS|{{AHORRO_ESTIMADO}}|de ahorro estimado|brand\nS|{{PLAZO}}|de instalación|light\nL|Nos encargamos de los trámites|Licencias, subvenciones y legalización.|light\nM|Monitoriza en la app|Producción y consumo en tiempo real.|light\nM|Garantía {{GARANTIA}}|{{CONDICIONES_GARANTIA}}|accent",
  B2B:"L|Conectividad que no para tu negocio|Fibra simétrica, respaldo 4G/5G y soporte prioritario.|dark\nS|{{SLA}}|de disponibilidad|brand\nS|{{VELOCIDAD}}|simétricos|light\nL|IP fija|Para tus servidores, cámaras y VPN.|light\nM|Gestor dedicado|Un interlocutor para toda tu cuenta.|light\nM|Migración sin cortes|Planificamos el cambio contigo fuera de tu horario de trabajo.|accent",
  Centralita:"L|Tu centralita, en la nube|Extensiones, colas y horarios desde un panel web.|dark\nS|{{N_EXTENSIONES}}|extensiones incluidas|brand\nS|App|Llama con el fijo desde el móvil|light\nL|Grabación y estadísticas|Mide cuántas llamadas pierdes y por qué.|light\nM|Números en toda España|Fijos geográficos y 900.|light\nM|Sin obra ni centralita física|Lo dejamos funcionando en {{PLAZO}}.|accent",
  Seg:"L|Tu negocio vigilado de noche|Cámaras con detección y aviso a la central receptora.|dark\nS|{{TIEMPO_RESPUESTA}}|de respuesta media|brand\nS|Niebla|Opcional contra robos|light\nL|Control de accesos|Quién entra y cuándo, desde la app.|light\nM|Cumple normativa|Grado {{GRADO_SEGURIDAD}} certificado.|light\nM|Estudio de seguridad gratuito|Visitamos tu local y te proponemos la protección justa.|accent"
};
const PR_STATS={
  Telco:"{{VELOCIDAD}}|de fibra simétrica\n{{PLAZO}}|para instalarla\n{{CLIENTES}}|clientes conectados",
  Alarmas:"{{TIEMPO_RESPUESTA}}|tiempo medio de respuesta\n{{HORARIO_CRA}}|central receptora\n{{CLIENTES}}|hogares protegidos",
  "Energía":"{{AHORRO_ESTIMADO}}|ahorro medio estimado\n{{N_INSTALACIONES}}|instalaciones realizadas\n{{GARANTIA}}|de garantía en paneles",
  B2B:"{{SLA}}|disponibilidad garantizada\n{{TIEMPO_RESPUESTA}}|respuesta ante incidencias\n{{EMPRESAS}}|empresas conectadas",
  Seguros:"{{AHORRO_MEDIO}}|ahorro medio al cambiar\n{{TIEMPO_PROPUESTA}}|para tener tu propuesta\n{{VALORACION}}|valoración de clientes"
};
const PR_PLANS_B2B=[{name:"Fibra Empresa",price:"{{PRECIO_1}}",unit:"€/mes + IVA",feats:"{{VELOCIDAD_1}} simétricos\nIP fija opcional\nSoporte en horario laboral",tag:"",cta:"Quiero esta"},{name:"Fibra + respaldo",price:"{{PRECIO_2}}",unit:"€/mes + IVA",feats:"{{VELOCIDAD_2}} simétricos\nRespaldo 4G/5G automático\nSoporte prioritario",tag:"La más elegida",cta:"Quiero esta"},{name:"Fibra dedicada",price:"{{PRECIO_3}}",unit:"€/mes + IVA",feats:"Caudal garantizado\nSLA {{SLA}}\nGestor dedicado",tag:"",cta:"Hablar con un gestor"}];

/* ===== VITRINA ===== */
prTpl("Vitrina · Fibra premium","vitrina","Telco","A","form","Página de producto premium: barra con «Contratar» siempre visible, hero centrado con teléfono, lo esencial en bento, cifras y tarifas.",
  [{type:"dx_subnav",props:{name:"Fibra {{VELOCIDAD}}",btn:"Contratar"}},{type:"dx_product",props:{kicker:"Fibra {{VELOCIDAD}}",headline:"Internet que no se nota.",highlight:"Porque simplemente va.",sub:"Fibra simétrica, router incluido e instalación en {{PLAZO}}. Precio final, sin sorpresas.",price:"{{PRECIO}}",illus:"wifi",cta:"Que me llamen"}},
   {type:"dx_tiles",props:{items:PR_TILES.Telco}},{type:"dx_stats",props:{items:PR_STATS.Telco}},{type:"da_plans",props:{title:"Elige tu velocidad."}},{type:"da_faq",props:{items:PR_S.Telco.faq}},{type:"da_cta",props:{title:"¿Hablamos? Te llamamos gratis."}},FOOT("da"),STK("da")]);
prTpl("Vitrina · Alarma inteligente","vitrina","Alarmas","A","form","Producto premium para seguridad: el kit como protagonista, ventajas en bento y estudio gratis como CTA.",
  [{type:"dx_subnav",props:{name:"Alarma {{NOMBRE_KIT}}",links:"Lo esencial>#esencial|Preguntas>#faq",btn:"Estudio gratis"}},{type:"dx_product",props:{kicker:"Alarma con central receptora",headline:"Tu casa, protegida.",highlight:"También cuando no estás.",sub:"Un experto estudia tu vivienda y te propone la protección justa. Instalación profesional y app incluida.",price:"{{PRECIO}}",priceNote:"{{CONDICIONES}}",illus:"shield",cta:"Quiero mi estudio gratis",link:""}},
   {type:"dx_tiles",props:{items:PR_TILES.Alarmas}},{type:"dx_media",props:{kicker:"Cómo funciona",title:"Salta la alarma. Actuamos.",text:"La central receptora verifica el aviso y, si hace falta, avisa a emergencias. Tú lo ves todo en la app.",checks:"Verificación en {{TIEMPO_RESPUESTA}}\nAviso a emergencias\nHistorial en la app",btn:"Pedir estudio gratis",illus:"shield"}},
   {type:"dx_stats",props:{items:PR_STATS.Alarmas}},{type:"da_faq",props:{items:PR_S.Alarmas.faq}},{type:"da_cta",props:{title:"Te llamamos y lo vemos juntos."}},FOOT("da"),STK("da")]);
prTpl("Vitrina · Placas solares","vitrina","Energía","A","form","Producto premium para autoconsumo: hero centrado, ahorro en bento, calculadora y estudio de tejado.",
  [{type:"dx_subnav",props:{name:"Autoconsumo solar",links:"Lo esencial>#esencial|Preguntas>#faq",btn:"Estudio gratis"}},{type:"dx_product",props:{kicker:"Autoconsumo solar",headline:"El sol paga tu factura.",highlight:"Tú solo la miras bajar.",sub:"Estudiamos tu tejado y tu consumo y te decimos cuánto ahorrarías antes de instalar nada.",price:"",illus:"bolt",cta:"Quiero mi estudio"}},
   {type:"dx_tiles",props:{items:PR_TILES["Energía"]}},{type:"dx_calc",props:{unit:"€/mes"}},{type:"dx_stats",props:{items:PR_STATS["Energía"]}},{type:"da_faq",props:{items:"¿Cuánto cuesta la instalación?|{{RESPUESTA}}\n¿Hay subvenciones?|{{RESPUESTA}}\n¿Qué pasa los días nublados?|{{RESPUESTA}}\n¿Cuánto tarda en amortizarse?|{{RESPUESTA}}"}},{type:"da_cta"},FOOT("da"),STK("da")]);

/* ===== NEOBANCO ===== */
prTpl("Neobanco · Seguro en minutos","neobanco","Seguros","A","form","Fintech para seguros: chip de confianza, garantías pegadas al CTA, nosotros vs. otros, pasos y cifras con su fuente.",
  [NAV("da"),{type:"da_hero",props:{eyebrow:"Comparamos por ti, gratis",headline:"Tu seguro,",highlight:"claro y más barato",sub:"Dinos qué tienes ahora y te llamamos con una propuesta que puedes comparar línea a línea.",price:"",checks:"Sin compromiso\nTe llama una persona\nSin papeleo",cardTitle:"Recibe tu propuesta",cardSub:"Déjanos tu teléfono y te llamamos en {{MINUTOS}} min.",cardBtn:"Quiero mi propuesta",illus:"umbrella",layout:"std"}},
   {type:"dx_seals"},{type:"dx_vs",props:{title:"Lo que cambia con nosotros"}},{type:"db_steps",props:{title:"En tres pasos",items:"Nos cuentas tu póliza actual|Un minuto, por teléfono.\nTe enviamos la comparativa|Coberturas y precio, una al lado de la otra.\nDecides tú|Si te encaja, nos ocupamos del cambio."}},
   {type:"dx_stats",props:{items:PR_STATS.Seguros}},{type:"da_faq",props:{items:PR_S.Seguros.faq}},{type:"da_cta",props:{title:"¿Te llamamos ahora?"}},FOOT("da"),STK("da")]);
prTpl("Neobanco · Tarifa de luz clara","neobanco","Energía","A","form","Fintech para energía: precio en grande, calculadora de ahorro, comparativa con tu compañía y tarifas.",
  [NAV("da"),Object.assign(ucHero("Energía"),{props:Object.assign({},PR_S["Energía"].hero,{illus:"bolt",layout:"std",eyebrow:"Sin permanencia · sin cortes"})}),{type:"dx_seals"},{type:"dx_calc",props:{unit:"€/mes"}},{type:"dx_vs",props:{title:"Tu factura, sin trampas",them:"Tu compañía actual"}},{type:"da_plans",props:{plans:PR_S["Energía"].plans}},{type:"da_faq",props:{items:PR_S["Energía"].faq}},{type:"da_cta"},FOOT("da"),STK("da")]);
prTpl("Neobanco · Móvil digital","neobanco","Telco","A","form","Fintech para telco: hero centrado con teléfono, lo esencial en bento, tarifas y garantías.",
  [NAV("da"),{type:"dx_product",props:{kicker:"Tarifa móvil",headline:"Tu móvil, sin letra pequeña.",highlight:"Desde el primer día.",sub:"Gigas, llamadas y precio final claros. Te ayudamos a traer tu número.",price:"{{PRECIO}}",illus:"wifi",cta:"Que me llamen",vis:"none"}},{type:"dx_seals"},
   {type:"dx_tiles",props:{kicker:"Por qué cambiarte",items:"L|Trae tu número|Hacemos la portabilidad sin cortes.|dark\nS|{{GB}}|para navegar|brand\nS|{{LLAMADAS}}|en llamadas|light\nM|Sin permanencia|{{CONDICIONES}}|light\nM|Atención por WhatsApp|En {{HORARIO}}.|accent"}},{type:"da_plans",props:{plans:[{name:"{{TARIFA_1}}",price:"{{PRECIO_1}}",unit:"€/mes",feats:"{{GB_1}}\nLlamadas {{LLAMADAS}}",tag:"",cta:"La quiero"},{name:"{{TARIFA_2}}",price:"{{PRECIO_2}}",unit:"€/mes",feats:"{{GB_2}}\nLlamadas {{LLAMADAS}}",tag:"La más elegida",cta:"La quiero"},{name:"{{TARIFA_3}}",price:"{{PRECIO_3}}",unit:"€/mes",feats:"{{GB_3}}\nLlamadas {{LLAMADAS}}",tag:"",cta:"La quiero"}]}},
   {type:"da_faq",props:{items:PR_S.Telco.faq}},{type:"da_cta"},FOOT("da"),STK("da","wa")]);

/* ===== NOCTURNO ===== */
prTpl("Nocturno · Fibra para empresas","nocturno","Telco","A","form","SaaS oscuro para B2B: barra de producto, hero centrado, cifras de servicio, bento y formulario en 2 pasos.",
  [{type:"dx_subnav",props:{name:"Fibra Empresas",links:"Servicio>#esencial|Tarifas>#tarifas|Preguntas>#faq",btn:"Hablar con un gestor"}},{type:"dx_product",props:{kicker:"Para empresas",headline:"Conectividad que no se cae.",highlight:"Ni un lunes a las nueve.",sub:"Fibra simétrica con respaldo automático y un gestor que conoce tu cuenta.",price:"{{PRECIO}}",priceUnit:"€/mes + IVA",priceNote:"{{CONDICIONES}}",illus:"wifi",cta:"Que me llame un gestor"}},
   {type:"dx_stats",props:{items:PR_STATS.B2B}},{type:"dx_tiles",props:{kicker:"Servicio",title:"Pensado para que tu equipo no lo note.",items:PR_TILES.B2B}},{type:"da_plans",props:{title:"Planes para tu negocio",plans:PR_PLANS_B2B}},{type:"dx_form2"},{type:"da_faq",props:{items:"¿Hay permanencia?|{{RESPUESTA}}\n¿Qué pasa si cae la fibra?|{{RESPUESTA}}\n¿Cuánto tarda la instalación?|{{RESPUESTA}}\n¿Puedo mantener mis números?|{{RESPUESTA}}"}},FOOT("da"),STK("da")]);
prTpl("Nocturno · Seguridad para negocios","nocturno","Alarmas","A","form","SaaS oscuro para seguridad de locales: hero centrado, bento de protección, cifras y estudio gratuito.",
  [NAV("da"),{type:"dx_product",props:{kicker:"Seguridad para negocios",headline:"Cierra tranquilo.",highlight:"Nosotros vigilamos.",sub:"Alarma, cámaras y control de accesos conectados a central receptora. Estudio de seguridad gratuito.",price:"{{PRECIO}}",priceUnit:"€/mes + IVA",illus:"shield",cta:"Quiero el estudio gratis"}},
   {type:"dx_tiles",props:{kicker:"Protección",title:"Todo tu local, en una sola app.",items:PR_TILES.Seg}},{type:"dx_stats",props:{items:PR_STATS.Alarmas}},{type:"dx_vs",props:{title:"Con central receptora vs. alarma sin conectar",them:"Alarma sin conectar"}},{type:"da_faq",props:{items:PR_S.Alarmas.faq}},{type:"da_cta",props:{title:"Te llamamos y vemos tu local."}},FOOT("da"),STK("da")]);
prTpl("Nocturno · Centralita en la nube","nocturno","Telco","A","form","SaaS oscuro para telefonía de empresa: producto centrado, bento de funciones y tarifas por extensión.",
  [{type:"dx_subnav",props:{name:"Centralita virtual",links:"Funciones>#esencial|Tarifas>#tarifas|Preguntas>#faq",btn:"Pedir demo"}},{type:"dx_product",props:{kicker:"Centralita virtual",headline:"Que ninguna llamada se pierda.",highlight:"Ni fuera de la oficina.",sub:"Colas, horarios, grabación y estadísticas desde un panel web. Sin obra y sin aparatos.",price:"{{PRECIO}}",priceUnit:"€/extensión/mes",illus:"wifi",cta:"Quiero una demo"}},
   {type:"dx_tiles",props:{kicker:"Funciones",title:"Todo lo que hace tu centralita.",items:PR_TILES.Centralita}},{type:"da_plans",props:{title:"Paga por extensión",plans:[{name:"Básica",price:"{{PRECIO_1}}",unit:"€/ext./mes",feats:"Llamadas {{MINUTOS_1}}\nColas y horarios\nApp móvil",tag:"",cta:"La quiero"},{name:"Profesional",price:"{{PRECIO_2}}",unit:"€/ext./mes",feats:"Llamadas {{MINUTOS_2}}\nGrabación\nEstadísticas",tag:"La más elegida",cta:"La quiero"},{name:"Avanzada",price:"{{PRECIO_3}}",unit:"€/ext./mes",feats:"Integración CRM\nIVR a medida\nGestor dedicado",tag:"",cta:"Hablar con ventas"}]}},
   {type:"dx_form2",props:{title:"Te preparamos una demo"}},{type:"da_faq",props:{items:"¿Puedo mantener mis números?|{{RESPUESTA}}\n¿Necesito comprar teléfonos?|{{RESPUESTA}}\n¿Hay permanencia?|{{RESPUESTA}}\n¿Cuánto tarda la puesta en marcha?|{{RESPUESTA}}"}},FOOT("da"),STK("da")]);
