/* ---------- PLANTILLAS ---------- */
const TEMPLATES={
  "Landing completa":["topbar","navbar","hero_split","logos","trust","features","imagetext","counters","steps","pricing","testimonials","security","gallery","faq","form","ctaband","stickycall","footer"],
  "Conversión (CRO)":["topbar","navbar","hero_form","logos","trust","features","imagetext","counters","security","testimonials","pricing","form","faq","ctaband","stickycall","footer"],
  "Confianza (seguridad)":["navbar","hero_split","logowall","security","counters","features","steps","testimonials","imagetext","form","faq","footer"],
  "Apple (literal)":["apple_nav","apple_hero","apple_bento","apple_showcase","apple_footer"],
  "Movistar (literal)":["mov_nav","mov_hero","mov_tarifas","stats","faq","mov_footer"],
  "T-Mobile (literal)":["tmo_nav","tmo_hero","tmo_plans","trust","faq","tmo_footer"],
  "O2 (literal)":["o2_nav","o2_hero","o2_tiles","stats","faq","o2_footer"],
  "MyTraffic (literal)":["mt_nav","mt_hero","mt_kpi","form","mt_footer"],
  "AB Tasty (literal)":["at_nav","at_hero","at_features","form","at_footer"],
  "Cliente · Jazztel":["jz_nav","jz_hero","jz_ventajas","jz_tarifas","jz_cobertura","faq","jz_footer"],
  "Cliente · MásMóvil":[{type:"tel_nav",props:{logo:"MÁSMÓVIL",cta:"Llámanos 91 922 96 00"}},{type:"tel_hero",props:{eyebrow:"Fibra y móvil",headline:"Fibra 500Mb + 2 Líneas Móviles con 50GB",sub:"El mejor precio en fibra y móvil, sin permanencia.",price:"34,90",cta:"Solicitar información"}},{type:"tel_ventajas",props:{title:"Sobran motivos para confiar en MásMóvil",items:"⚡|Rapidez|Fibra de alta velocidad para toda la casa.\n🎁|Instalación gratis|Sin coste de alta ni de router.\n📶|Cobertura 5G|Datos a máxima velocidad estés donde estés."}},{type:"tel_tarifas",props:{title:"Otras tarifas destacadas",plans:[{name:"Fibra + Móvil",price:"14,90",feat:"Oferta de entrada",cta:"Solicitar información"},{name:"Fibra 500Mb + 2 Móviles",price:"34,90",feat:"2 líneas · 50GB",cta:"Solicitar información"},{name:"Fibra 1Gb + Móvil",price:"39,90",feat:"Máxima velocidad",cta:"Ver más tarifas"}]}},{type:"tel_cobertura",props:{title:"Elige cómo comprobar tu cobertura de fibra"}},"faq",{type:"tel_footer",props:{company:"MásMóvil"}}],
  "Cliente · Simyo":[{type:"tel_nav",props:{logo:"simyo",cta:"Contactar"}},{type:"tel_hero",props:{eyebrow:"Oferta Especial simyo",headline:"Fibra + Móvil y Smartphone ¿Qué más quieres?",sub:"Configura tu tarifa a tu medida, sin líos.",price:"",priceNote:"",cta:"Quiero esta tarifa"}},{type:"tel_ventajas",props:{title:"Con simyo, más opciones y menos líos",items:"📺|TV incluida|Series, cine, infantil, deporte y más.\n🛠️|Tú la configuras|Crea tu propia tarifa de fibra y móvil.\n📶|Cobertura|Comprueba tu fibra en segundos."}},{type:"tel_tarifas",props:{title:"Tarifas destacadas",plans:[{name:"Fibra + Móvil",price:"—",feat:"Configúrala a tu medida",cta:"Quiero esta tarifa"},{name:"Fibra + Móvil + TV",price:"—",feat:"Con contenidos incluidos",cta:"Quiero esta tarifa"},{name:"Solo Móvil",price:"—",feat:"Sin permanencia",cta:"Solicitar información"}]}},{type:"tel_cobertura",props:{title:"Compruébalo",sub:"Introduce tu dirección y comprobamos tu cobertura de fibra."}},"faq",{type:"tel_footer",props:{company:"simyo"}}],
  "Cliente · Yoigo":[{type:"tel_nav",props:{logo:"Yoigo",cta:"Contactar"}},{type:"tel_hero",props:{eyebrow:"Fibra 1 Gb",headline:"La fibra óptica más rápida de Yoigo",sub:"Con 1 Gb, vuela. La fibra más rápida al mejor precio.",price:"29,90",cta:"Quiero esta tarifa"}},{type:"tel_ventajas",props:{title:"Motivos para elegir Yoigo",items:"⚡|La más rápida|Fibra de 1 Gb simétrica.\n🎁|Router sin coste|Te lo enviamos gratis.\n📶|Fibra o ADSL|Cobertura donde la necesites."}},{type:"tel_tarifas",props:{title:"Tarifas destacadas",plans:[{name:"Fibra + Móvil",price:"29,90",feat:"1 línea",cta:"La quiero"},{name:"Fibra 1Gb + 2 Móviles",price:"39,90",feat:"Máxima velocidad",cta:"Esta me encaja"},{name:"Línea extra",price:"1,75",feat:"Añade líneas",cta:"Solicitar información"}]}},{type:"tel_cobertura",props:{title:"Consultar cobertura",sub:"Comprueba si tienes fibra o ADSL de Yoigo."}},"faq",{type:"tel_footer",props:{company:"Yoigo"}}],
  "Cliente · Vodafone":[{type:"tel_nav",props:{logo:"Vodafone",cta:"Llama Gratis"}},{type:"tel_hero",props:{eyebrow:"Fibra, Móvil y TV",headline:"Fibra 600MB, 2 líneas móviles ilimitadas y TV",sub:"Con todo el entretenimiento incluido. ¡Te llamamos gratis!",price:"",priceNote:"",cta:"¡Te llamamos Gratis!"}},{type:"tel_ventajas",props:{title:"Detalles que marcan la diferencia",items:"📺|Entretenimiento incluido|Los mejores contenidos hasta 2027.\n📶|Cobertura Vodafone|Comprueba tu cobertura en casa.\n📱|Líneas ilimitadas|Datos ilimitados a máxima velocidad."}},{type:"tel_tarifas",props:{title:"Otras tarifas destacadas",plans:[{name:"Fibra + Móvil",price:"—",feat:"2 líneas ilimitadas",cta:"Llamadme"},{name:"Fibra + Móvil + TV",price:"—",feat:"Entretenimiento incluido",cta:"Llamadme"},{name:"Solo Fibra",price:"—",feat:"Alta velocidad",cta:"Solicitar información"}]}},{type:"tel_cobertura",props:{title:"Comprueba si tienes cobertura Vodafone en tu casa"}},"faq",{type:"tel_footer",props:{company:"Vodafone"}}],
  "Cliente · Lowi":[{type:"tel_nav",props:{logo:"Lowi",cta:"Llámanos"}},{type:"tel_hero",props:{eyebrow:"Fibra y móvil",headline:"Fibra y móvil de Lowi al mejor precio",sub:"Sencillo, sin permanencia y con la red de Vodafone.",price:"",priceNote:"",cta:"Lo quiero"}},{type:"tel_ventajas",props:{title:"Por qué Lowi",items:"💶|Precio simple|Sin sorpresas ni permanencia.\n📶|Red Vodafone|Cobertura de primer nivel.\n🛠️|A tu medida|Configura tu fibra y móvil."}},{type:"tel_tarifas",props:{title:"Tarifas destacadas",plans:[{name:"Fibra + Móvil",price:"—",feat:"Sin permanencia",cta:"Lo quiero"},{name:"Fibra + 2 Móviles",price:"—",feat:"Para toda la familia",cta:"Lo quiero"},{name:"Solo Móvil",price:"—",feat:"Datos a tu gusto",cta:"Solicitar información"}]}},{type:"tel_cobertura",props:{title:"Comprueba tu cobertura"}},"faq",{type:"tel_footer",props:{company:"Lowi"}}],
  "Cliente · MásAhorro":[{type:"tel_nav",props:{logo:"MásAhorro",cta:"Llámanos"}},{type:"tel_hero",props:{eyebrow:"Fibra y móvil",headline:"Más Fibra, Más Móvil, Más Ahorro",sub:"Fibra 500Mb y 2 líneas con 50GB al mejor precio.",price:"",priceNote:"",cta:"¡Lo quiero!"}},{type:"tel_ventajas",props:{title:"Por qué MásAhorro",items:"💶|Máximo ahorro|El mejor precio en fibra y móvil.\n📶|Cobertura|Comprueba la velocidad en tu hogar.\n📱|Fibra + Móvil + TV|Todo lo que necesitas junto."}},{type:"tel_tarifas",props:{title:"Tarifas destacadas",plans:[{name:"Fibra + Móvil",price:"—",feat:"500Mb · 50GB",cta:"¡Lo quiero!"},{name:"Fibra + 2 Móviles",price:"—",feat:"Para la familia",cta:"¡Lo quiero!"},{name:"Solo Fibra",price:"—",feat:"Alta velocidad",cta:"Solicitar información"}]}},{type:"tel_cobertura",props:{title:"Comprueba tu cobertura"}},"faq",{type:"tel_footer",props:{company:"MásAhorro"}}],
  "Cliente · Prosegur":[{type:"al_nav",props:{logo:"Prosegur",cta:"Llamar gratis",wa:"WhatsApp"}},{type:"al_hero",props:{gift:"Cámara 360º gratis",headline:"Contrata ahora y llévate una SuperCámara Inteligente sin coste para siempre",sub:"Alarma conectada con Central Receptora y aviso a las autoridades.",cta:"¡La quiero!"}},{type:"al_porque",props:{title:"¿Por qué elegir nuestra SuperSeguridad?",items:"🛰️|Vigilancia 24/7|Central receptora conectada con la policía.\n📷|Equipamiento de última generación|SuperCámara y detección inteligente.\n📱|Control desde el móvil|Gestiona tu alarma esté donde estés."}},{type:"al_garantias",props:{title:"Nuestras garantías",items:"🛡️|Garantía antirrobo|Te cubrimos ante una intrusión.\n🏠|Garantía anti-ocupación|Protección frente a okupación.\n🤝|Compromiso cliente|El cliente en el centro, sin letra pequeña."}},"faq",{type:"al_footer",props:{company:"Prosegur"}}],
  "Captación · llamada":["navbar","hero_split","logos","features","steps","stats","form","faq","ctaband","stickycall","footer"],
  "Captación · formulario arriba":["topbar","navbar","hero_form","hero_video","logos","features","testimonials","imagetext","faq","footer"],
  "Oferta / urgencia":["topbar","navbar","hero_center","pricing","stats","testimonials","form","faq","stickycall","footer"]
};
